#pragma bank 255
#include <gb/gb.h>
#include "world/world.h"
/* Only gb.h (BANKREF), not engine.h: through gbdk/emu_debug.h it adds 2 bytes of bank 0 and of RAM to every file
   that includes it, and 96 of these files overflowed bank 0.
   PLAY GAME 2 world row 77: screens x = 0..127 at y = 77, 128 bytes each = one full 16 KB ROM bank.
   Per screen: 9 rows of 10 metatile chars (legend: ow_metatiles in assets/tilesets/ts_overworld.c),
   the HUD name and the text of its sign ("" = no sign). Format: assets/world/world.h */
BANKREF(world_r77)
const wscreen_t world_r77[WORLD_W] = {
/* 000,77 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 001,77 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 002,77 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 003,77 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 004,77 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 005,77 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 006,77 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 007,77 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 008,77 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 009,77 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 010,77 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 011,77 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 012,77 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 013,77 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 014,77 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 015,77 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 016,77 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 017,77 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 018,77 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 019,77 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 020,77 */ {
    "ssssssssss"
    "~sssssscss"
    "~sssssssss"
    "~~~sssssss"
    "~~~~~sssss"
    "~~~~~~sssc"
    "~~~~~~~sss"
    "~~~~~~~~ss"
    "~~~~~~~~ss"
  , "COAST", "" },
/* 021,77 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 022,77 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssscssssc"
  , "DUNE WASTES", "" },
/* 023,77 */ {
    "csssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 024,77 */ {
    "ssssssssss"
    "ssssssssss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssscss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 025,77 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "sscsssssss"
  , "DUNE WASTES", "" },
/* 026,77 */ {
    "ssMMMMMMMM"
    "ssMMMMMMMM"
    "ssMMMMMMMM"
    "ssMMMMMMMM"
    "sscMMMMMMM"
    "ssssMMMMMM"
    "ssssssMMMM"
    "ssssssssss"
    "ssssssssss"
  , "GRAY PEAKS", "" },
/* 027,77 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "sMMMMMMMMM"
    "ssssMMMMMM"
  , "GRAY PEAKS", "" },
/* 028,77 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 029,77 */ {
    "MMMMMMMsss"
    "MMMMMMMMss"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 030,77 */ {
    "ssssssssss"
    "scssssssss"
    "sssssssscs"
    "MMssssssMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 031,77 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "MMMMssssss"
    "MMMMMscsss"
    "MMMMMMssss"
    "MMMMMMMsss"
    "MMMMMMMMMs"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 032,77 */ {
    "*.Rr=.Rr.*"
    "..HD=.HD.."
    "....=....."
    "...ppppS.."
    "===pppp==="
    "...pppp..."
    "..Rr=.Rr.."
    "..HD=.HD.."
    "*...=....*"
  , "EASTMOUTH", "WELCOME TO EASTMOUTH" },
/* 033,77 */ {
    "ssssssssss"
    "scssssssss"
    "ssssssssss"
    "sssssssssc"
    "=========="
    "ssssssssss"
    "ssssssssss"
    "cssssssssc"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 034,77 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssc====="
    "======ssss"
    "sss=ssssss"
    "sss=ssssss"
    "sss=ssssss"
    "sss=ssssss"
  , "DUNE WASTES", "" },
/* 035,77 */ {
    "sssscsMMMM"
    "sssssssMMM"
    "ssssssssss"
    "=========="
    "ssssssssss"
    "scssssssss"
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 036,77 */ {
    "MMMMMMM=MM"
    "MMMMMMM=MM"
    "sscssMM=MM"
    "========MM"
    "sssssssMMM"
    "ssssssssMM"
    "sscsssssMM"
    "ssssssssMM"
    "ssssssssMM"
  , "GRAY PEAKS", "" },
/* 037,77 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 038,77 */ {
    "MMMMMsssss"
    "MMMMMMssss"
    "MMMMMMssss"
    "MMMMMMMsss"
    "MMMMMMMMss"
    "MMMMMMMMMs"
    "MMMMMMMMMs"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 039,77 */ {
    "ssssssssss"
    "csssssssss"
    "csssssssss"
    "ssssssscss"
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "Msssssssss"
  , "DUNE WASTES", "" },
/* 040,77 */ {
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 041,77 */ {
    "ssscssssss"
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 042,77 */ {
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "sscsssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 043,77 */ {
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 044,77 */ {
    "ssssssssss"
    "ssscssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 045,77 */ {
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 046,77 */ {
    "sssssscsss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
  , "DUNE WASTES", "" },
/* 047,77 */ {
    "ssssssssss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 048,77 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssssscs"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 049,77 */ {
    "scssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 050,77 */ {
    "~~ssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 051,77 */ {
    "ssssssssss"
    "ssssssssss"
    "sssssssss~"
    "sssssssss~"
    "sssssssss~"
    "sssssssss~"
    "scsssssss~"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 052,77 */ {
    "ssssssssss"
    "~~~~~sssss"
    "~~~~~~~sss"
    "~~~~~~~sss"
    "~~~~~~~sss"
    "~~~~~~ssss"
    "~~~~~~ssss"
    "~~~~~sssss"
    "~~~~ssssss"
  , "COAST", "" },
/* 053,77 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 054,77 */ {
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
  , "DUNE WASTES", "" },
/* 055,77 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "sssssssssc"
  , "DUNE WASTES", "" },
/* 056,77 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 057,77 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 058,77 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "sssssssssc"
  , "DUNE WASTES", "" },
/* 059,77 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 060,77 */ {
    "ssssssssss"
    "ssssssssss"
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 061,77 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 062,77 */ {
    "ssssssssss"
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 063,77 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 064,77 */ {
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssscsssscs"
  , "DUNE WASTES", "" },
/* 065,77 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 066,77 */ {
    "*.Rr=.Rr.*"
    "..HD=.HD.."
    "....=....."
    "...ppppS.."
    "===pppp==="
    "...pppp..."
    "..Rr=.Rr.."
    "..HD=.HD.."
    "*...=....*"
  , "MOONFORD", "WELCOME TO MOONFORD" },
/* 067,77 */ {
    "ss==ssssss"
    "ss=sssssss"
    "ss=sssssss"
    "ss=scsssss"
    "===sssssss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "scssssssss"
  , "DUNE WASTES", "" },
/* 068,77 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "ssssssssss"
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 069,77 */ {
    "ssssssssss"
    "csssssssss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
    "sssscsssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 070,77 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
  , "DUNE WASTES", "" },
/* 071,77 */ {
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sscsssscss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 072,77 */ {
    "ssssssssss"
    "csssssssss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
    "sssssscsss"
  , "DUNE WASTES", "" },
/* 073,77 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
  , "DUNE WASTES", "" },
/* 074,77 */ {
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "csssssssss"
    "ssssssscss"
    "sssssssssc"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 075,77 */ {
    "ssssssssss"
    "csssssssss"
    "ssssssssss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssssscs"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 076,77 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssscssssss"
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 077,77 */ {
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "sscsssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 078,77 */ {
    "ssssssssss"
    "ssssssssss"
    "scsssscsss"
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 079,77 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssscssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 080,77 */ {
    "ssssssssss"
    "sssscssssc"
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 081,77 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 082,77 */ {
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 083,77 */ {
    "sscsssssss"
    "sscsssssss"
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 084,77 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 085,77 */ {
    "ssssscs==="
    "sssssssss="
    "ssssssssss"
    "csssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 086,77 */ {
    "ssssssssss"
    "==csssssss"
    "s=sscsssss"
    "s=ssssssss"
    "s=ssssssss"
    "s=ssssssss"
    "s==sssssss"
    "ss=sssssss"
    "ss==ssssss"
  , "DUNE WASTES", "" },
/* 087,77 */ {
    "ssssssssss"
    "ssssssssss"
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 088,77 */ {
    "ssssscssss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
  , "DUNE WASTES", "" },
/* 089,77 */ {
    "ssssssssss"
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 090,77 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssscss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 091,77 */ {
    "cssssssssc"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 092,77 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 093,77 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 094,77 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssssscs"
  , "DUNE WASTES", "" },
/* 095,77 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 096,77 */ {
    "sss=ssssss"
    "sss=ssssss"
    "sss=ssssss"
    "sss=ssssss"
    "sss=ssssss"
    "sss=ssssss"
    "sss=ssssss"
    "sss=ssssss"
    "sss=ssssss"
  , "DUNE WASTES", "" },
/* 097,77 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "sssssssscs"
  , "DUNE WASTES", "" },
/* 098,77 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 099,77 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 100,77 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "sssssssscs"
  , "DUNE WASTES", "" },
/* 101,77 */ {
    "sssMMMMMMM"
    "sssMMMMMMM"
    "ssssMMMMMM"
    "ssssMMMMMM"
    "sssssMMMMM"
    "sssssMMMMM"
    "sssssMMMMM"
    "sssssMMMMM"
    "ssssssMMMM"
  , "GRAY PEAKS", "" },
/* 102,77 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 103,77 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 104,77 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 105,77 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 106,77 */ {
    "MMMMMMMMMs"
    "MMMMMMMMMs"
    "MMMMMMMMMs"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMss"
    "MMMMMMMcss"
  , "GRAY PEAKS", "" },
/* 107,77 */ {
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
    "csss=sssss"
    "ssss=sscss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
  , "DUNE WASTES", "" },
/* 108,77 */ {
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 109,77 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "csssssssss"
  , "DUNE WASTES", "" },
/* 110,77 */ {
    "sssssssMMM"
    "sssssssssM"
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "ssssssssss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 111,77 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "ssMMMMMMMM"
    "ssMMMMMMMs"
    "sssMMMMsss"
    "ssscMsssss"
    "ssscssssss"
    "ssssssssss"
  , "GRAY PEAKS", "" },
/* 112,77 */ {
    "Msssssssss"
    "Msssssssss"
    "Msssssssss"
    "Msscssssss"
    "ssssssss=="
    "ssssssss=s"
    "ssssssss=s"
    "sssss====s"
    "cssss=ssss"
  , "DUNE WASTES", "" },
/* 113,77 */ {
    "*.Rr=.Rr.*"
    "..HD=.HD.."
    "....=....."
    "...ppppS.."
    "===pppp==="
    "...pppp..."
    "..Rr=.Rr.."
    "..HD=.HD.."
    "*...=....*"
  , "RIVERCROSS", "WELCOME TO RIVERCROSS" },
/* 114,77 */ {
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
    "ssssssssss"
    "=========="
    "ssssssssss"
    "ssssssssss"
    "ssscssssss"
    "ssssscssss"
  , "DUNE WASTES", "" },
/* 115,77 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "===scssssc"
    "ss======sc"
    "sssssss==="
    "ssssssssss"
    "sssscsssss"
  , "DUNE WASTES", "" },
/* 116,77 */ {
    "sscsssssss"
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "=ssssscsss"
    "==sssssscs"
    "s========="
  , "DUNE WASTES", "" },
/* 117,77 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssscss"
    "=========="
  , "DUNE WASTES", "" },
/* 118,77 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "sscsssssss"
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
    "===sssssss"
  , "DUNE WASTES", "" },
/* 119,77 */ {
    "sscs=sssss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
    "scss=sssss"
    "ssss=sssss"
    "ssss=sssss"
  , "DUNE WASTES", "" },
/* 120,77 */ {
    "ssssssssss"
    "ssssssssss"
    "csssscssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 121,77 */ {
    "ss~~~~~~~~"
    "ss~~~~~~~~"
    "s~~~~~~~~~"
    "s~~~~~~~~~"
    "s~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "COAST", "" },
/* 122,77 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 123,77 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 124,77 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 125,77 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 126,77 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 127,77 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
};
