#pragma bank 255
#include <gb/gb.h>
#include "world/world.h"
/* Only gb.h (BANKREF), not engine.h: through gbdk/emu_debug.h it adds 2 bytes of bank 0 and of RAM to every file
   that includes it, and 96 of these files overflowed bank 0.
   PLAY GAME 2 world row 72: screens x = 0..127 at y = 72, 128 bytes each = one full 16 KB ROM bank.
   Per screen: 9 rows of 10 metatile chars (legend: ow_metatiles in assets/tilesets/ts_overworld.c),
   the HUD name and the text of its sign ("" = no sign). Format: assets/world/world.h */
BANKREF(world_r72)
const wscreen_t world_r72[WORLD_W] = {
/* 000,72 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 001,72 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 002,72 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 003,72 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 004,72 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 005,72 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 006,72 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 007,72 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 008,72 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 009,72 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 010,72 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 011,72 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 012,72 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 013,72 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 014,72 */ {
    "~~~~~~~~ss"
    "~~~~~~~sss"
    "~~~~~~~sss"
    "~~~~~~~ss."
    "~~~~~~~ss."
    "~~~~~~ss.."
    "~~~~~~ssss"
    "~~~~~~ssss"
    "~~~~~~ssss"
  , "COAST", "" },
/* 015,72 */ {
    "s........."
    ".........,"
    ".........."
    ",....,...."
    "..,...,,.."
    ",..ss.,..."
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "PLAINS", "" },
/* 016,72 */ {
    "...*...*.."
    ".***..*.*."
    "..*.....*."
    "....*..*.."
    ".*........"
    "...*..*..."
    "sssss*...."
    "ssssssss.."
    "ssssssssss"
  , "MEADOWS", "" },
/* 017,72 */ {
    ",........."
    "..,......."
    "...,....,."
    ".....,...,"
    "...,...,.,"
    ".......sss"
    "......ssss"
    ".....sssss"
    ".....sssss"
  , "PLAINS", "" },
/* 018,72 */ {
    "..,...,..."
    ".........."
    ".........."
    ",........s"
    ".sssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssss~~~~~~"
    "ss~~~~~~~~"
  , "PLAINS", "" },
/* 019,72 */ {
    ".,=ss~~~~~"
    ".s=ss~~~~~"
    "ss=ss~~~~~"
    "ss=ss~~~~~"
    "ss=ss~~~~~"
    "ss=ss~~~~~"
    "ss=s~~~~~~"
    "~~#~~~~~~~"
    "~s=~~~~~~s"
  , "COAST", "" },
/* 020,72 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~ssssss"
    "~sssssssss"
    "ssssssssss"
    "ssssssssss"
  , "COAST", "" },
/* 021,72 */ {
    "~~~~~~~sss"
    "~~~~~~~sss"
    "~~~~~~sss,"
    "~~~~~sss.."
    "~~~~sss..."
    "~~~sss...."
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "COAST", "" },
/* 022,72 */ {
    "s...*.*.**"
    ".*...**..."
    "...*.*...."
    "....*.**.."
    ".....**.*."
    "....*..**."
    "sssssss.*."
    "ssssssssss"
    "ssssssssss"
  , "MEADOWS", "" },
/* 023,72 */ {
    ".........."
    ".........."
    "..,......."
    "....,....."
    ".....,...."
    ".........."
    "*.,.....,."
    ".........."
    "ss.,......"
  , "PLAINS", "" },
/* 024,72 */ {
    "....,...,,"
    "..,...,.,."
    ".........."
    ".........."
    ".........."
    ".........."
    ".........."
    ".........."
    "...,......"
  , "PLAINS", "" },
/* 025,72 */ {
    "....=....."
    "....=,...."
    "....=..,.."
    "....=...,."
    ".T..=....."
    "....=T...."
    "...==....."
    "...=T.T..."
    "...=..T..."
  , "KINGS ROAD", "" },
/* 026,72 */ {
    ".....T...T"
    ".........."
    ".........."
    ".........."
    ".......T.M"
    ".T.......M"
    ".........M"
    "......TT.M"
    "........TM"
  , "PLAINS", "" },
/* 027,72 */ {
    ".MMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 028,72 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 029,72 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 030,72 */ {
    "MMMMM.T.TT"
    "MMMMMT..T."
    "MMMMM.T..."
    "MMMMMTTT.."
    "MMMMM.TTT."
    "MMMMMTT..T"
    "MMMMM.TTTT"
    "MMMMT.TTTT"
    "MMMM...TTT"
  , "GRAY PEAKS", "" },
/* 031,72 */ {
    "T...T..TT."
    "TT..T.T..T"
    "T.TT......"
    "T.T.....T."
    "T.....T..T"
    "TTTT...TT."
    "....T.T..."
    "TT.T.TTTTT"
    "TTT.T.T.TT"
  , "OLD FOREST", "" },
/* 032,72 */ {
    "....=..,.."
    "T..S=....."
    "T...=....."
    "....=....."
    ".T.T=,...."
    "....=,...."
    "TT..=....,"
    ".T..=....."
    ".T.T=..,.,"
  , "KINGS ROAD", "TO RIVERHOLM 2N 1W" },
/* 033,72 */ {
    ".........."
    ".........."
    ",........."
    ".........."
    ".....,...."
    ".......,.."
    "......,..."
    ",........."
    ".......,.."
  , "PLAINS", "" },
/* 034,72 */ {
    "...MMMMMMM"
    "....MMMMMM"
    ".....MMMMM"
    ".....MMMMM"
    ".....MMMMM"
    ".....MMMMM"
    ".....MMMMM"
    ".....MMMMM"
    ".....MMMMM"
  , "GRAY PEAKS", "" },
/* 035,72 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 036,72 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 037,72 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 038,72 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 039,72 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 040,72 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 041,72 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 042,72 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMss"
    "MMMMMMMMss"
  , "GRAY PEAKS", "" },
/* 043,72 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMs"
    "MMMMMMMMMs"
    "MMMMMMMMss"
    "MMMMMMMsss"
    "MMMMMMMsss"
    "ssssMMssss"
    "ssssssssss"
    "ssssssssss"
  , "GRAY PEAKS", "" },
/* 044,72 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssscssssc"
    "sssssssssc"
  , "DUNE WASTES", "" },
/* 045,72 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 046,72 */ {
    "ssssssssss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 047,72 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "sscsssssss"
    "sssssssssc"
  , "DUNE WASTES", "" },
/* 048,72 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 049,72 */ {
    "scsssssss~"
    "sssssssss~"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "csssscssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 050,72 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "ss~~~~~~~~"
    "sss~~~~~~~"
    "sssss~~~~~"
    "ssssss~~~~"
    "sssssss~~~"
    "ssssssss~~"
  , "COAST", "" },
/* 051,72 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~ss"
    "~~~~~~ssss"
    "~~~~~sssss"
    "~~~~ssssss"
    "~~~~ssssss"
    "~~~sssssss"
    "~~ssssssss"
  , "COAST", "" },
/* 052,72 */ {
    "~~~~~~~~~~"
    "~sss~~~~~~"
    "sssss~~~~~"
    "sssssss~~s"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssscss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 053,72 */ {
    "~~~~ssssss"
    "~~~sssssss"
    "~sssssssss"
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 054,72 */ {
    "=sssssssss"
    "=sssssssss"
    "=sssssssss"
    "=cssssssss"
    "=cssssssss"
    "=ssssssscs"
    "=sssssssss"
    "=sssssssss"
    "=sssssssss"
  , "DUNE WASTES", "" },
/* 055,72 */ {
    "scssssssss"
    "ssssssssss"
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "cssssssssc"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 056,72 */ {
    "sssss....."
    "sssssss..."
    "sssscssss."
    "sssscsssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 057,72 */ {
    ".........."
    "........,."
    ".........."
    "s...,....."
    "scs..,,..."
    "sssc.,...."
    "ssssss...."
    "ssssssss.."
    "ssssssssss"
  , "PLAINS", "" },
/* 058,72 */ {
    ".........,"
    "..,....,.."
    ".......,.."
    ".........."
    ".........."
    "..,......."
    "....,....."
    ".....,...."
    "s........s"
  , "PLAINS", "" },
/* 059,72 */ {
    ".........."
    ".,........"
    "..,....,.."
    "....,...,,"
    "..,...,.,."
    ".........."
    ".........."
    "....ssssss"
    "ssssssssss"
  , "PLAINS", "" },
/* 060,72 */ {
    ".,...,...."
    ".........."
    ".........."
    ".........."
    ".....,...."
    ".......,.."
    ".s......,."
    "ssssssss.."
    "ssssssssss"
  , "PLAINS", "" },
/* 061,72 */ {
    ",...,....."
    ",....,...."
    ".......,.."
    ".....,...,"
    ".........."
    ".........."
    ".........."
    ".........."
    ".,........"
  , "PLAINS", "" },
/* 062,72 */ {
    ".........."
    ",........."
    ".,,......."
    ".,......,."
    ".........."
    ".........."
    "....,....."
    "........,."
    ".........."
  , "PLAINS", "" },
/* 063,72 */ {
    "...T....T."
    ".........."
    ".....T..T."
    "........T."
    ",........."
    ".,........"
    ".........."
    "....,....."
    ".........."
  , "PLAINS", "" },
/* 064,72 */ {
    "...T.TTTT."
    "T...TT...T"
    "..T.T.TTTT"
    "...T.TT.TT"
    "....TT.T.T"
    "...TT.TTT."
    ".......T.T"
    ".....TT.T."
    "...T..T.TT"
  , "OLD FOREST", "" },
/* 065,72 */ {
    ".TTT.TTTTT"
    "TT...TTTTT"
    "TTTTTTTT.T"
    "T..TTTTTTT"
    "TT..TT.TTT"
    "T.TTT.T..."
    "TTTTTTTTT."
    ".TTTT.TTT."
    "TTTTTTTTTT"
  , "OLD FOREST", "" },
/* 066,72 */ {
    "..TTTT.TTT"
    "TTTTTTTT.T"
    "TTT..TTTTT"
    "T..TTTTTTT"
    "TT.TTTTT.T"
    "TTTTT..TT."
    "T.TTTTTTTT"
    "TT.TTTTTTT"
    "TTTTTTTTTT"
  , "OLD FOREST", "" },
/* 067,72 */ {
    "..T.=....."
    "TTTT=TTTT."
    ".TTT=.TT.T"
    "T.TT=..TT."
    "TTTT=.TT.T"
    "T.TT=T.TTT"
    ".T..=TTT.T"
    ".TTT=TTTTT"
    "T.T.=TTT.T"
  , "OLD FOREST", "" },
/* 068,72 */ {
    ".T.TTT..T."
    "T.T.T....T"
    ".TTT...T.."
    ".T.TT..T.T"
    "...T.TT..."
    "T..T.T..T."
    "TT.T.....T"
    "..TTTTT..."
    "TTT....T.T"
  , "OLD FOREST", "" },
/* 069,72 */ {
    "T.T..T.TT."
    ".TT..T...T"
    "TT.T......"
    "T.TT..T..T"
    "...T.TTTT."
    ".TT.T..T.."
    "..T.TTTTT."
    "TT.T...TT."
    "...TT..T.."
  , "OLD FOREST", "" },
/* 070,72 */ {
    "TT.T.T.T.."
    "..T.TTT..."
    "TT..T.TT.."
    "T.T...T.TT"
    "T.TT..T.T."
    "T.TTT.T..."
    ".T...PTTTT"
    "T.TPP....."
    "T.PPP.PP.T"
  , "OLD FOREST", "" },
/* 071,72 */ {
    "..T.TT..T."
    "T..TT.T.T."
    "T.TT.TT..T"
    "......T.TT"
    ".T..TT.T.."
    "..T..T.TTT"
    "...TT.T..."
    "T.T...TT.s"
    ".TTTTsssss"
  , "OLD FOREST", "" },
/* 072,72 */ {
    "..TT.T.TTT"
    "...TT....T"
    "..TT.T...."
    "TT.T.TT..s"
    "T.TT.TTsss"
    "TT..ssssss"
    "TTssssssss"
    "ssssssssss"
    "sssssscsss"
  , "PLAINS", "" },
/* 073,72 */ {
    ".....sssss"
    "T..sssssss"
    ".sssssssss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 074,72 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssssssc"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 075,72 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
  , "DUNE WASTES", "" },
/* 076,72 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 077,72 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "sssssssssc"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 078,72 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
  , "DUNE WASTES", "" },
/* 079,72 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 080,72 */ {
    "sss=ssssss"
    "sss=ssssss"
    "css=ssssss"
    "sss=ssssss"
    "sss=ssssss"
    "sss=ssssss"
    "ssc==sssss"
    "ssss==sssc"
    "sssss=ssss"
  , "DUNE WASTES", "" },
/* 081,72 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 082,72 */ {
    "ssssssssss"
    "ssscssssss"
    "ssssssssss"
    "sssssssss="
    "sssssssss="
    "ssssscsss="
    "ssssssss=="
    "ssssssss=s"
    "sssssss==s"
  , "DUNE WASTES", "" },
/* 083,72 */ {
    "s==ssssss."
    "==ssssssss"
    "=sssssssss"
    "=sssssssss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 084,72 */ {
    "....*.**.."
    "........*."
    "s.*..*.*.*"
    "sc........"
    "sss.....*."
    "ssss..*..."
    "sssss*...*"
    "ssssss.***"
    "cssssc.*.*"
  , "MEADOWS", "" },
/* 085,72 */ {
    ".*.......*"
    "*...**..*."
    ".**..*...*"
    "*.*..*.*.."
    "*..*......"
    "..*.**.*.*"
    "..*.*....."
    "*.......**"
    "..*....*.."
  , "MEADOWS", "" },
/* 086,72 */ {
    ".........."
    ".*.*.*..*."
    "....P....."
    ".*.*......"
    "..*.....PP"
    "*.....*.P."
    "...*...PPP"
    ".**P..P.P."
    "..*.....P."
  , "MEADOWS", "" },
/* 087,72 */ {
    ".P........"
    "P.*......."
    "...P.P...."
    ".P.P......"
    ".....P.PP."
    "..P..P.P.."
    "PPPP......"
    "PPP..P...."
    "...P.P..P."
  , "PLAINS", "" },
/* 088,72 */ {
    "....P.P..."
    ".......P.."
    "P...P.P..."
    ".....P...."
    "P..P......"
    "......P..."
    ".PP.PPP..P"
    "P....P.P.."
    "PPPP...P.."
  , "PLAINS", "" },
/* 089,72 */ {
    "...P...**."
    "......P.P."
    "....P.*..*"
    "..P.....P."
    ".P...P..P."
    "PPPPPPP..."
    ".P.PPP..P."
    ".P....P.PP"
    "P...P..PP."
  , "PLAINS", "" },
/* 090,72 */ {
    ".*...*...."
    ".P.P...P.P"
    "........P."
    "PP.P.PP..."
    "P.P....P.P"
    ".PP.PP.PPP"
    ".P.P....P."
    ".P.PPPP..."
    "..PP...P.."
  , "PLAINS", "" },
/* 091,72 */ {
    "P........."
    ".......P.."
    ".....P...."
    "....P...P."
    "...P..PTT."
    "..P.P.T.T."
    "....P....T"
    "P..P......"
    "......T..T"
  , "PLAINS", "" },
/* 092,72 */ {
    "......T..."
    ".........."
    "....T.T..."
    "...T......"
    ".......TT."
    "......T..."
    "....T....."
    ".T...TT..s"
    "...T.T..ss"
  , "PLAINS", "" },
/* 093,72 */ {
    "T.T......."
    ".T......T."
    ".......Tss"
    "..T...ssss"
    "..T.ssscss"
    "..ssssscss"
    ".sssssssss"
    "ssssssssss"
    "sscsssssss"
  , "DUNE WASTES", "" },
/* 094,72 */ {
    "T.ssssssss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
    "sssssscsss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 095,72 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 096,72 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "csssssssss"
    "ssssssscss"
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 097,72 */ {
    "csssssssss"
    "ssssssssss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 098,72 */ {
    "ssssssssss"
    "ssssssssss"
    "ssscssssss"
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 099,72 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "sscsssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 100,72 */ {
    "ssssssssss"
    "scsssscsss"
    "sssssscsMM"
    "ssssssssMM"
    "ssssssssMM"
    "scssssssMM"
    "ssssssssMM"
    "sssssssssM"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 101,72 */ {
    "ssssssssss"
    "MMMsssssss"
    "MMMMMMMMss"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 102,72 */ {
    "sssscssssc"
    "sssssssssc"
    "ssssssssss"
    "MMssssssss"
    "MMMscsssss"
    "MMMMMsssss"
    "MMMMMMssss"
    "MMMMMMMsss"
    "MMMMMMMMMs"
  , "GRAY PEAKS", "" },
/* 103,72 */ {
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssMMMM"
  , "DUNE WASTES", "" },
/* 104,72 */ {
    "ssssssss.."
    "ssssssssss"
    "ssssssssss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "MMMMMsssss"
  , "DUNE WASTES", "" },
/* 105,72 */ {
    "=.,....,.."
    "=s.......,"
    "==sssss,.."
    "s=ssssssss"
    "s=ssssssss"
    "s==sssssss"
    "ss=sssssss"
    "ss==ssssss"
    "sss===ssss"
  , "DUNE WASTES", "" },
/* 106,72 */ {
    "..,......."
    "...,,....."
    ".,.,......"
    "sss......."
    "sssssssss."
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 107,72 */ {
    "....MMMMMM"
    ".........."
    ",........."
    "..,......."
    "...,......"
    "ssss......"
    "ssssssss.."
    "ssssssssss"
    "ssssssssss"
  , "PLAINS", "" },
/* 108,72 */ {
    "MMMMMMMMMM"
    ",..MMMMMMM"
    "....MMMMMM"
    ".....MMMMM"
    ".....MMMMM"
    "......MMMM"
    ".......MMM"
    "s.......MM"
    "scs......."
  , "GRAY PEAKS", "" },
/* 109,72 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 110,72 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMM......"
    "MMMM......"
    "MMM......."
    "MMM......."
    "MMM.,....."
    "MMM...,..."
  , "GRAY PEAKS", "" },
/* 111,72 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "...MMMMMMM"
    "....MMMMM."
    "....MMMM.."
    ".....MMM.."
    ".........."
  , "GRAY PEAKS", "" },
/* 112,72 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "..MMMMMMMM"
    "..MMMMMMMM"
    "..MMMMMMMM"
    "..MMMMMMMM"
    ".,..MMMMMM"
  , "GRAY PEAKS", "" },
/* 113,72 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMM..sssss"
    "MMM..sssss"
  , "GRAY PEAKS", "" },
/* 114,72 */ {
    "Msssssssss"
    "Msssssssss"
    "Msssssssss"
    "Msssssssss"
    "Msssssssss"
    "Msssssssss"
    "ssssssssss"
    "ssMMMMMMMs"
    "sMMMMMMMMM"
  , "DUNE WASTES", "" },
/* 115,72 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "ssssssssss"
    "ssssssssss"
    "MMssssssss"
  , "DUNE WASTES", "" },
/* 116,72 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssssscs"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 117,72 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
  , "DUNE WASTES", "" },
/* 118,72 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 119,72 */ {
    "*.Rr=.Rr.*"
    "..HD=.HD.."
    "....=....."
    "...ppppS.."
    "===pppp==="
    "...pppp..."
    "..Rr=.Rr.."
    "..HD=.HD.."
    "*...=....*"
  , "GOLDMERE", "WELCOME TO GOLDMERE" },
/* 120,72 */ {
    "....*.s~~~"
    ".....*s~~~"
    "sssssss~~~"
    "sssssss~~~"
    "sssssss~~~"
    "ssssssss~~"
    "ssssssss~~"
    "sssssssss~"
    "ssssscsss~"
  , "DUNE WASTES", "" },
/* 121,72 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 122,72 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 123,72 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 124,72 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 125,72 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 126,72 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 127,72 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
};
