#pragma bank 255
#include <gb/gb.h>
#include "world/world.h"
/* Only gb.h (BANKREF), not engine.h: through gbdk/emu_debug.h it adds 2 bytes of bank 0 and of RAM to every file
   that includes it, and 96 of these files overflowed bank 0.
   PLAY GAME 2 world row 75: screens x = 0..127 at y = 75, 128 bytes each = one full 16 KB ROM bank.
   Per screen: 9 rows of 10 metatile chars (legend: ow_metatiles in assets/tilesets/ts_overworld.c),
   the HUD name and the text of its sign ("" = no sign). Format: assets/world/world.h */
BANKREF(world_r75)
const wscreen_t world_r75[WORLD_W] = {
/* 000,75 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 001,75 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 002,75 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 003,75 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 004,75 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 005,75 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 006,75 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 007,75 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 008,75 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 009,75 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 010,75 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 011,75 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 012,75 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~s"
    "~~~~~~~~~s"
    "~~~~~~~~~s"
  , "OPEN SEA", "" },
/* 013,75 */ {
    "~~~~~~~~~~"
    "~~~sssss~~"
    "~~ssssss~~"
    "~ssssss~~~"
    "sssssss~~~"
    "sssssss~~~"
    "sssssss~~~"
    "sssssss~~~"
    "ssssss~~~~"
  , "COAST", "" },
/* 014,75 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 015,75 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 016,75 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 017,75 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 018,75 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 019,75 */ {
    "~~~~ssssss"
    "~~~~~sssss"
    "~~~~~sssss"
    "~~~~ssssss"
    "~~~~ssssss"
    "~~~~ssssss"
    "~~~~ssssss"
    "~~~~~sssss"
    "~~~~~sssss"
  , "COAST", "" },
/* 020,75 */ {
    "ssssssssss"
    "sscsssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 021,75 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "ssssssssss"
    "sssssssssc"
  , "DUNE WASTES", "" },
/* 022,75 */ {
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
  , "DUNE WASTES", "" },
/* 023,75 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 024,75 */ {
    "ssssssssss"
    "ssssssssss"
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sscsssscss"
    "ssssssscss"
  , "DUNE WASTES", "" },
/* 025,75 */ {
    "sss=ssssMM"
    "sss=sssssM"
    "sss=ssssss"
    "css=ssssss"
    "sss==sscss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
  , "DUNE WASTES", "" },
/* 026,75 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "sMMMMMMMMM"
    "sMMMMMMMMM"
    "sMMMMMMMMM"
    "sMMMMMMMMM"
    "sMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 027,75 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 028,75 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 029,75 */ {
    "MMMMT.TTTT"
    "MMMTT.T.TT"
    "MMMTTTTTTT"
    "MMMT.TTPPP"
    "MMTTTTTPP."
    "MMscssssss"
    "MMscssssss"
    "MMMsssssss"
    "MMMsssssss"
  , "PLAINS", "" },
/* 030,75 */ {
    "TTTTTTTTTT"
    "TT.TTTT..T"
    "T.TTTTTTTT"
    "PPT.TTT.ss"
    "PPssssssss"
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "sscsssssss"
  , "DUNE WASTES", "" },
/* 031,75 */ {
    "TT.....T.T"
    "TT.T..TT.."
    ".TTTTsssss"
    "ssssssssss"
    "scsssscsss"
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
  , "DUNE WASTES", "" },
/* 032,75 */ {
    ".T..=....."
    "...T=scsss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
    "sssc=sssss"
    "ssss=cssss"
    "ssss=sssss"
  , "DUNE WASTES", "" },
/* 033,75 */ {
    "...,.....M"
    "sssss...MM"
    "sssssssMMM"
    "sssscsMMMM"
    "sssssMMMMM"
    "sssssMMMMM"
    "sssssMMMMM"
    "sssscsMMMM"
    "sssssssMMM"
  , "GRAY PEAKS", "" },
/* 034,75 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 035,75 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 036,75 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMM."
    "MMMMMMMMM."
    "MMMMMMMM.,"
    "MMMMMMMM.."
    "MMMMMMMM.."
    "MMMMMMMM.."
    "MMMMMMMMM."
  , "GRAY PEAKS", "" },
/* 037,75 */ {
    "M........."
    "......,..."
    ".........."
    "..,......."
    "...,,....."
    ".,.,......"
    "....**...."
    "...**.*..."
    "..*..**..."
  , "PLAINS", "" },
/* 038,75 */ {
    ".......,.."
    ",....,...,"
    ".....,...."
    ".........."
    ".........."
    ",........."
    "..,......."
    "...,......"
    "..*......s"
  , "PLAINS", "" },
/* 039,75 */ {
    ".........,"
    ".........."
    ",....,..ss"
    "..,...,sss"
    ",...,sssss"
    "....ssssss"
    "..ssssssss"
    ".sssssssss"
    "ssssssssss"
  , "PLAINS", "" },
/* 040,75 */ {
    ".sscsssscs"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 041,75 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 042,75 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 043,75 */ {
    "scssssssss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 044,75 */ {
    "ssssssssss"
    "ssssssssss"
    "cssssssssc"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 045,75 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 046,75 */ {
    "scssssssss"
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
  , "DUNE WASTES", "" },
/* 047,75 */ {
    "ssssssssss"
    "sscsssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 048,75 */ {
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssscssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 049,75 */ {
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 050,75 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 051,75 */ {
    "ssssssss~~"
    "sssssssss~"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 052,75 */ {
    "~~~sssssss"
    "~~sssssss~"
    "sssssss~~~"
    "sssss~~~~~"
    "sssss~~~~~"
    "sssss~~~~~"
    "sssss~~~~~"
    "sssss~~~~~"
    "ssss~~~~~s"
  , "COAST", "" },
/* 053,75 */ {
    "ssssssssss"
    "ssssssssss"
    "~sssssssss"
    "~sssssssss"
    "~sssssssss"
    "~sssssssss"
    "~sssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 054,75 */ {
    "sss==sssss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sscss"
    "ssss=sssss"
  , "DUNE WASTES", "" },
/* 055,75 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
  , "DUNE WASTES", "" },
/* 056,75 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 057,75 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "ssssssscss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 058,75 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
  , "DUNE WASTES", "" },
/* 059,75 */ {
    "ssssssssss"
    "ssssssssss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 060,75 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "ssssssscss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 061,75 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 062,75 */ {
    "ssssssssss"
    "scssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 063,75 */ {
    "sss*T..*.."
    "ssssssssss"
    "ssssssssss"
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "ssssssssss"
    "sssssssscs"
  , "DUNE WASTES", "" },
/* 064,75 */ {
    "sssscsssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssscssssss"
  , "DUNE WASTES", "" },
/* 065,75 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 066,75 */ {
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "scsssscsss"
    "sssssscsss"
  , "DUNE WASTES", "" },
/* 067,75 */ {
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=scsss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
  , "DUNE WASTES", "" },
/* 068,75 */ {
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssscssssc"
    "sssssssssc"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 069,75 */ {
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
  , "DUNE WASTES", "" },
/* 070,75 */ {
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 071,75 */ {
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "sscsssssss"
    "sssssssssc"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 072,75 */ {
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
  , "DUNE WASTES", "" },
/* 073,75 */ {
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "csssscssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
  , "DUNE WASTES", "" },
/* 074,75 */ {
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "sssscsssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 075,75 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssscsssscs"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssscssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 076,75 */ {
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 077,75 */ {
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 078,75 */ {
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "scssssssss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 079,75 */ {
    "ssssssssss"
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 080,75 */ {
    "ssssssssss"
    "sssscsssss"
    "sssscsssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 081,75 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 082,75 */ {
    "sscsssscss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 083,75 */ {
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 084,75 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 085,75 */ {
    "c=ssssssss"
    "s=ssssscss"
    "s=sssssssc"
    "s=ssssssss"
    "s=ssssssss"
    "s=ssssssss"
    "s=ssssssss"
    "s=ssssssss"
    "s=ssssssss"
  , "DUNE WASTES", "" },
/* 086,75 */ {
    "ssssssssss"
    "ssssssssss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 087,75 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssssssc"
  , "DUNE WASTES", "" },
/* 088,75 */ {
    "csssssssss"
    "sscsssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 089,75 */ {
    "ssssssssss"
    "scssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 090,75 */ {
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 091,75 */ {
    "sssscsssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 092,75 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 093,75 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 094,75 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssscssssss"
  , "DUNE WASTES", "" },
/* 095,75 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 096,75 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 097,75 */ {
    "*.Rr=.Rr.*"
    "..HD=.HD.."
    "....=....."
    "...ppppS.."
    "===pppp==="
    "...pppp..."
    "..Rr=.Rr.."
    "..HD=.HD.."
    "*...=....*"
  , "HAWKBURY", "WELCOME TO HAWKBURY" },
/* 098,75 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 099,75 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 100,75 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssscssssss"
  , "DUNE WASTES", "" },
/* 101,75 */ {
    "sMMMMMMMMM"
    "sMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 102,75 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 103,75 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 104,75 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 105,75 */ {
    "MMMMMMMMs="
    "MMMMMMMMMs"
    "MMMMMMMMMs"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 106,75 */ {
    "==scssssss"
    "s=ssssssss"
    "s==sssssss"
    "ss=sssssss"
    "ss=sscssss"
    "ss===sssss"
    "ssss=sssss"
    "Msss=sssss"
    "Mscs=sssss"
  , "DUNE WASTES", "" },
/* 107,75 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 108,75 */ {
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "csssscssss"
    "ssssscssss"
  , "DUNE WASTES", "" },
/* 109,75 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "sMMMMMMMMM"
    "ssMMMMMMMM"
    "ssMMMMMMMM"
    "ssMMMMMMMM"
    "ssMMMMMMMM"
    "ssMMMMMMMM"
    "ssMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 110,75 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 111,75 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMs"
    "MMMMMMMMMs"
    "MMMMMMMMMs"
    "MMMMMMMMMs"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 112,75 */ {
    "MMssssscss"
    "Msssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 113,75 */ {
    "sssMMMMMMM"
    "sssMMMMMMM"
    "ssssMMMMMM"
    "ssssMMMMMM"
    "ssssMMMMMM"
    "scssMMMMMM"
    "scssMMMMMM"
    "ssssMMMMMM"
    "ssssMMMMMM"
  , "GRAY PEAKS", "" },
/* 114,75 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 115,75 */ {
    "MMMMMMMMMM"
    "MMMMssssss"
    "MMMMssssss"
    "MMMMssssss"
    "MMMMcsssss"
    "MMMMcsssss"
    "MMMMssssss"
    "MMMMssssss"
    "MMMsssssss"
  , "GRAY PEAKS", "" },
/* 116,75 */ {
    "MMMMssssss"
    "sssscsssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "ssscssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 117,75 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sscsssscss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 118,75 */ {
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 119,75 */ {
    "ssss=sssss"
    "ssss=sssss"
    "ssss=cssss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=cssss"
    "ssss=sssss"
    "ssss=sssss"
  , "DUNE WASTES", "" },
/* 120,75 */ {
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "csssssssss"
    "ssssssscss"
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 121,75 */ {
    "sss~~~~~~~"
    "sss~~~~~~~"
    "sss~~~~~~~"
    "ss~~~~~~~~"
    "ss~~~~~~~~"
    "ss~~~~~~~~"
    "ss~~~~~~~~"
    "ss~~~~~~~~"
    "sss~~~~~~~"
  , "COAST", "" },
/* 122,75 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 123,75 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 124,75 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 125,75 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 126,75 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 127,75 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
};
