#pragma bank 255
#include <gb/gb.h>
#include "world/world.h"
/* Only gb.h (BANKREF), not engine.h: through gbdk/emu_debug.h it adds 2 bytes of bank 0 and of RAM to every file
   that includes it, and 96 of these files overflowed bank 0.
   PLAY GAME 2 world row 53: screens x = 0..127 at y = 53, 128 bytes each = one full 16 KB ROM bank.
   Per screen: 9 rows of 10 metatile chars (legend: ow_metatiles in assets/tilesets/ts_overworld.c),
   the HUD name and the text of its sign ("" = no sign). Format: assets/world/world.h */
BANKREF(world_r53)
const wscreen_t world_r53[WORLD_W] = {
/* 000,53 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 001,53 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 002,53 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 003,53 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 004,53 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 005,53 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 006,53 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 007,53 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 008,53 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 009,53 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 010,53 */ {
    "~~~~~~~~~s"
    "~~~~~~~~~s"
    "~~~~~~~~~s"
    "~~~~~~~sss"
    "~~~~~sssss"
    "~~~~ssssss"
    "~~ssssssss"
    "~~sssss.ss"
    "~sssss...."
  , "COAST", "" },
/* 011,53 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssss~~ss"
  , "DUNE WASTES", "" },
/* 012,53 */ {
    "sssss....."
    "ssssss...."
    "ssssss...."
    "ssssss,..."
    "ssssss...."
    "ss........"
    "s.....,..."
    "ss..,....."
    "ss.,......"
  , "PLAINS", "" },
/* 013,53 */ {
    ".........."
    ".......T.."
    ".......,.."
    ".........T"
    ".........."
    ".....,...T"
    ".........."
    "...,.,...."
    ".........."
  , "PLAINS", "" },
/* 014,53 */ {
    ".T.T......"
    "....TTTTT."
    "...T.....T"
    ".TTT.TT.T."
    "..TT.T.T.."
    ".T.....T.T"
    "T.....TT.."
    "...TT.T..."
    ".T...T..TT"
  , "PLAINS", "" },
/* 015,53 */ {
    ".T.TT.TTTT"
    ".TTT.T.T.T"
    ".T...TT.TT"
    "TTTTTTT.TT"
    ".T.TT.TTTT"
    ".TT.T.TTT."
    "...T.TT.TT"
    "T..TTT.TT."
    "TT...TTT.T"
  , "OLD FOREST", "" },
/* 016,53 */ {
    "TTTTTTTTTT"
    "TTT.TTTT.."
    "TTTTTTTTTT"
    "T.TT.TTTT."
    "..TTT....."
    "...TT.T..T"
    "TTT.TTTT.T"
    "..T.TT..TT"
    "T.TTT..T.T"
  , "OLD FOREST", "" },
/* 017,53 */ {
    "TT........"
    "..T.T....."
    ".T........"
    "T...T....."
    "T.T......."
    "T........T"
    "...T......"
    "TTTT......"
    ".T.T......"
  , "PLAINS", "" },
/* 018,53 */ {
    "...,.====="
    ".......T.="
    "........T="
    ".,...T.T.="
    "......T..="
    ".T.......="
    ".........="
    "...T...T.="
    ".........="
  , "KINGS ROAD", "" },
/* 019,53 */ {
    ".....T.T.."
    "..T.T.T.TT"
    ".......T.T"
    ".....T.T.."
    "...T.....T"
    "..T...T..T"
    ".T..TTTT.."
    "T.T...T..T"
    "=.T....T.."
  , "KINGS ROAD", "" },
/* 020,53 */ {
    ".TT..T..T."
    "..T..TT..."
    "..T.T...TT"
    "T.TTT....T"
    ".TT.TTTTT."
    ".T.TT...T."
    "..TT.TT.TT"
    "..TTT.TT.T"
    "..T.TTTTTT"
  , "OLD FOREST", "" },
/* 021,53 */ {
    "TTTTTT.T.T"
    ".TTTTTT.T."
    "TT..TTT.T."
    "T.T..TTTTT"
    "TTTT.T.TTT"
    "TTTTTTTTTT"
    "TTTTTT.TTT"
    "TTTT.TT..."
    "TTT.TTTTT."
  , "OLD FOREST", "" },
/* 022,53 */ {
    "TTTT.T.TTT"
    "T.TT.T.T.."
    "TTTT.TTT.."
    "..T.TT.TTT"
    ".TTTT.TT.."
    "T.TTTTT.TT"
    "T.T.TTTT.T"
    "TTTT.TTTTT"
    ".TT.T.TT.."
  , "OLD FOREST", "" },
/* 023,53 */ {
    ".TT.TTTTTT"
    ".TTTTT.TTT"
    ".TTTTT..TT"
    "TT.TTTT.T."
    ".TTTTTTTTT"
    ".TTTTTTTT."
    "T.TTTTT.TT"
    "T..TTT.TTT"
    ".TTT...TTT"
  , "OLD FOREST", "" },
/* 024,53 */ {
    ".T.T.TT.T."
    ".T.TTTT.TT"
    "TTT..T.TT."
    "TTT.TTTT.T"
    "TTTT.TTTTT"
    "TTTT.T..TT"
    "T..TTTT.T."
    "TT..TT.T.T"
    "TTTTTTTT.T"
  , "OLD FOREST", "" },
/* 025,53 */ {
    "T...T.T..."
    "T....T...."
    "TTTT..TTTT"
    "T...T.T..."
    ".TT.TTT..T"
    "T....T.T.."
    "TTTT...T.."
    "T...T....."
    ".T..TTTT.T"
  , "OLD FOREST", "" },
/* 026,53 */ {
    "..T.T.T..T"
    ".TT.....T."
    ".T...T...."
    "T..TTT...."
    ".T.T.T..T."
    ".T....T..."
    "T.......T."
    "...T..T..."
    "..T...T..."
  , "PLAINS", "" },
/* 027,53 */ {
    "........T."
    "TT.T.TT..T"
    "T......T.T"
    "....TT.TTT"
    "...T....TT"
    ".T.T.TT..T"
    "..TT...T.."
    "T.T....TTT"
    "....T..T.."
  , "PLAINS", "" },
/* 028,53 */ {
    ".T..TTTTTT"
    "TTT.T.TTTT"
    "TTTTTTTTTT"
    ".TTTTTTTTT"
    "TTT.TTTTTT"
    "TT.TTTTT.."
    "...TTTTTTT"
    "TTTTTT.TTT"
    ".TT.TTTTT."
  , "OLD FOREST", "" },
/* 029,53 */ {
    "TT.TTTTTTT"
    "TTTT.TTTTT"
    "TTTTTTTTTT"
    "TTTTTTTTTT"
    "TTT.TTTTTT"
    "TTTT.TTT.T"
    "TTTTTT.TTT"
    "T..TTTTTTT"
    ".TTTTTTTTT"
  , "OLD FOREST", "" },
/* 030,53 */ {
    "T.TTTT.T.T"
    "TTTTTTTTTT"
    "TTTTTTTTTT"
    ".TTTTTTTTT"
    "TTTTT.TTTT"
    "TTT...TTTT"
    "TTTTTTTTT."
    "TT.TTTTTTT"
    "TTT..TTTTT"
  , "OLD FOREST", "" },
/* 031,53 */ {
    "TTTTTTT.TT"
    "TTTTTTTTTT"
    "TTTTTTTTTT"
    "TTTTTT.TTT"
    "T..TTTT.TT"
    "TTTTTTTTT."
    "TTTT..TTTT"
    "TT..TTTTTT"
    "TTTTTTTTT."
  , "OLD FOREST", "" },
/* 032,53 */ {
    "TTTT=TTTTT"
    "TTTT=TTTTT"
    "TTT==TTTTT"
    "TTT=TTTT.T"
    "T.T=TT...T"
    "TTT=TTTTTT"
    "TTT=T.TTTT"
    "TTT=TT..TT"
    "TTT=T.TTTM"
  , "OLD FOREST", "" },
/* 033,53 */ {
    "TTTTTTTTTT"
    "TTTTTTTTTT"
    "TTTTTMMMMM"
    "TTTMMMMMMM"
    "TTMMMMMMMM"
    "TTMMMMMMMM"
    "TMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 034,53 */ {
    "TTTTTTTTTT"
    "TTTTTT.TTT"
    "MMMMMMMMTT"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 035,53 */ {
    "TTTTTTTTTT"
    "TTTTTTTTTT"
    "T.TTTTT..T"
    "..TTTTTTTT"
    "MMMMM.TTTT"
    "MMMMMMMT.."
    "MMMMMMMMTT"
    "MMMMMMMMMT"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 036,53 */ {
    "TTTTTT.T.."
    "TT.TTTTTT."
    "TTT.TT...T"
    "TTTTT.TTTT"
    "..TTTTT.TT"
    "TTTTTTTT.T"
    "TTTTT.TTT."
    "TT..TT.T.T"
    "TTTTTTT.T."
  , "OLD FOREST", "" },
/* 037,53 */ {
    "T.T...T..."
    "..T......."
    "........T."
    "TTT.T....."
    "...T..T.TT"
    "TT..TT...."
    "T..TT.T..."
    "TTT.T.TT.."
    ".TTTT.T.*."
  , "PLAINS", "" },
/* 038,53 */ {
    ".T..=.T..."
    "...T=..TT."
    ".T..=T.T.T"
    ".T..=.T.TT"
    "....=..TT."
    "....=.T..T"
    "...T=....."
    "....=....."
    "....=....T"
  , "KINGS ROAD", "" },
/* 039,53 */ {
    "TT......T."
    "..T......."
    "....T..T.."
    "......T..T"
    "T......TT."
    "T......T.T"
    "T.T.T....T"
    ".T..T....."
    ".TTTTT...."
  , "PLAINS", "" },
/* 040,53 */ {
    "..T...T..."
    ".T..T...T."
    "....T....T"
    ".TTT...T.."
    "...TT..T.T"
    "......T..."
    "T....T...."
    ".........T"
    ".....TT..."
  , "PLAINS", "" },
/* 041,53 */ {
    "TT...T...."
    "T.TTTTTTTT"
    ".TT.TTT..T"
    "TT.T.TTT.."
    "T.TTT.T..T"
    "...T.TTTT."
    ".TT.T..TTT"
    "..T.TTTTTT"
    "TT.T.T.TTT"
  , "OLD FOREST", "" },
/* 042,53 */ {
    "....T.TTT."
    "TT.T.T.T.."
    "T.TTTTT..."
    "TT..T.TT.."
    "T.T...T.TT"
    "TTTT..T.T."
    "T.TTT.T..."
    "TTT..TTTTT"
    "T.TTT....."
  , "OLD FOREST", "" },
/* 043,53 */ {
    ".T.T.T...."
    "..T.TT...."
    "TT.TT.T..."
    "T.TT.TT..."
    "......T.T."
    ".T..TT.T.."
    "..T..T.TTT"
    "...TT.T..."
    "T.T...TT.."
  , "PLAINS", "" },
/* 044,53 */ {
    "T..T......"
    "..T..T.***"
    "...TT....*"
    "..*T.T...."
    "TT.T.TT..."
    "T..T......"
    "TT........"
    ".T........"
    "T..T.T...."
  , "PLAINS", "" },
/* 045,53 */ {
    "*.Rr=.Rr.*"
    "..HD=.HD.."
    "....=....."
    "...ppppS.."
    "===pppp==="
    "...pppp..."
    "..Rr=.Rr.."
    "..HD=.HD.."
    "*...=....*"
  , "ASHWOOD", "WELCOME TO ASHWOOD" },
/* 046,53 */ {
    ".....,...."
    "......,..."
    ".........."
    "...,.....,"
    ".........."
    "....,...ss"
    "....,.ssss"
    "......ssss"
    ".....sssss"
  , "PLAINS", "" },
/* 047,53 */ {
    ".........."
    ".........."
    ".........."
    ".........."
    ".........."
    "ssssss...."
    "sssssss..."
    "ssssssss.."
    "ssssssss.."
  , "PLAINS", "" },
/* 048,53 */ {
    ".ssssssss,"
    "..ssssss.."
    "..ssssss.."
    "..ssssss.."
    "...sss.,.."
    ".......,.."
    ".........."
    ".........."
    ".....,...,"
  , "PLAINS", "" },
/* 049,53 */ {
    ".........."
    "..ss......"
    "..,s...*.."
    ".........."
    ".....*.**."
    ".........*"
    ".,.*..*.*."
    "..*......."
    ".*.......*"
  , "MEADOWS", "" },
/* 050,53 */ {
    "....**...."
    ".....*.*.*"
    "......*..*"
    ".*....*.*."
    "..*......."
    ".*...**..."
    "*.**..*..."
    ".*.*..*.,."
    ".*..*....."
  , "MEADOWS", "" },
/* 051,53 */ {
    ".**.T....."
    "*...TT...."
    "......T..."
    "P.......T."
    ",........."
    "....T.T..T"
    ".....T..T."
    "..,.T....."
    "...,.....T"
  , "PLAINS", "" },
/* 052,53 */ {
    ".T......T."
    "T.....TT.T"
    "....T..T.T"
    "TT...TT.T."
    "..T.T...TT"
    ".T.TTTTT.T"
    "....T.TT.T"
    "T.T.TT.T.T"
    "T.....T.TT"
  , "OLD FOREST", "" },
/* 053,53 */ {
    "TTTTTTTTTT"
    ".TTTTT.TTT"
    "TTTTTTTTTT"
    "T.TTTT.TTT"
    ".TTTTTTTTT"
    ".TTT.TT.TT"
    "TTTTTTTTTT"
    "TTT..TTTTT"
    ".TTTTT.TTT"
  , "OLD FOREST", "" },
/* 054,53 */ {
    "TT.TTTTTTT"
    "TTTTTTTTTT"
    "TTTTTTTTTT"
    "TTTTTTTTTT"
    "TTT.TTTTTT"
    "TTTT.TTTTT"
    ".TTTTT.TTT"
    "..TTTTTTTT"
    "T.T.TTTTTT"
  , "OLD FOREST", "" },
/* 055,53 */ {
    "T.T.TTTTss"
    "TTTTTTTTTT"
    "TT.T.TTTT."
    ".TT.TTTTTT"
    "TTT.TTT.TT"
    "TTTTTTT.TT"
    "T.TTTT..TT"
    ".TTTTTTTT."
    "TT.TTT..T."
  , "OLD FOREST", "" },
/* 056,53 */ {
    "TTT.ssssss"
    "TTTTssssss"
    "TTTTssssss"
    "TTTsssssss"
    ".sssssssss"
    "Tsssssss=="
    "Tssssss==s"
    "TTssss==ss"
    "TTssss=sss"
  , "DUNE WASTES", "" },
/* 057,53 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "=========="
    "=ssssss~~~"
    "=sssss~~~~"
    "ssssss~~~~"
    "sssss~~~~~"
    "sssss~~~~~"
  , "DUNE WASTES", "" },
/* 058,53 */ {
    "s......T.T"
    "ss........"
    "ssss....T."
    "====sss..."
    "~~~======="
    "~~~~~~~~~s"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "COAST", "" },
/* 059,53 */ {
    "T...TT.T.T"
    ".T.T...TT."
    "T.TTTTT.T."
    ".S.T.TT.TT"
    "=========="
    "ssssssssss"
    "~~~~ssssss"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "KINGS ROAD", "TO WHITEHILL 3E" },
/* 060,53 */ {
    ".TT.T.T..."
    "TT..T.T.T."
    "TTT....T.."
    "T...T.T..."
    "=========="
    "ssss......"
    "ssssT.T..."
    "~sssTTT..T"
    "~sss.T...."
  , "KINGS ROAD", "" },
/* 061,53 */ {
    "....T....."
    "...T......"
    ".........."
    "....T....."
    "=========="
    ".T........"
    "T..T......"
    ".T...T...."
    ".T....,..."
  , "KINGS ROAD", "" },
/* 062,53 */ {
    "*.Rr=.Rr.*"
    "..HD=.HD.."
    "....=....."
    "...ppppS.."
    "===pppp==="
    "...pppp..."
    "..Rr=.Rr.."
    "..HD=.HD.."
    "*...=....*"
  , "WHITEHILL", "WELCOME TO WHITEHILL" },
/* 063,53 */ {
    "......,..."
    ",........."
    ".......,ss"
    "....ssssss"
    "..ssssssss"
    ".ssss~~~~~"
    "ss~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "COAST", "" },
/* 064,53 */ {
    "......ssss"
    "..ssssssss"
    "sssssssss~"
    "sssss~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "COAST", "" },
/* 065,53 */ {
    "s~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 066,53 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 067,53 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 068,53 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 069,53 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 070,53 */ {
    "~~~~~~~~ss"
    "~~~~~~~~~s"
    "~~~~~~~~~s"
    "~~~~~~~~~s"
    "~~~~~~~~~s"
    "~~~~~~~~~s"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "COAST", "" },
/* 071,53 */ {
    "s.PP=PPPPP"
    "ssP==PPPPP"
    "ssP=PPPPPP"
    "ssP=PPPPP."
    "sss=PPPPPP"
    "sss=PPP.PP"
    "sss=P.PPPP"
    "~ss=PPPPPP"
    "~~s=PPPPPP"
  , "PINE WOODS", "" },
/* 072,53 */ {
    ".PPPP.P.PP"
    "PPPPPPPPPP"
    "PPPPPPPPPP"
    "PPPPPPPPPP"
    "PPPP.PPPPP"
    "PP...PPPPP"
    "PPPPPPPP.P"
    "P.PPPPPPPP"
    "PP..PPPPPP"
  , "PINE WOODS", "" },
/* 073,53 */ {
    "PPPPPP.PP."
    "PP.PPPPP.P"
    "PP.PPPPPP."
    ".PPPP.PPPP"
    "..PPPP.PP."
    "PPPPPP.P.P"
    "PPP..PP.PP"
    "P..PPP.PP."
    "PP..PPPP.P"
  , "PINE WOODS", "" },
/* 074,53 */ {
    ".........."
    "P.P.P....,"
    "...P.....,"
    "PP........"
    ".........."
    "....P....."
    "......,..."
    "P......,.."
    "P........."
  , "PLAINS", "" },
/* 075,53 */ {
    ".,........"
    "...,......"
    "....,....,"
    "......,..."
    "....,...,."
    ".........."
    ".........."
    ".........."
    ".........."
  , "PLAINS", "" },
/* 076,53 */ {
    "...,...,.."
    ".........."
    ".........."
    ",,........"
    ",......P.."
    ".........P"
    ".........."
    "...,......"
    ".......,.."
  , "PLAINS", "" },
/* 077,53 */ {
    "..P.P.P..P"
    "..P....P.P"
    ".....P...P"
    "....P..P.."
    ".....P.P.."
    "..P.PPP..."
    "PP....PP.."
    "..P......P"
    "..PP....P."
  , "PLAINS", "" },
/* 078,53 */ {
    "..T.T....T"
    "T.T.TTTT.."
    "...TT...T."
    ".T.T.T..T."
    "..T.TT..T."
    "T..TT.T.T."
    "T.TT.TT..T"
    "......T.TT"
    "....TT.T.."
  , "OLD FOREST", "" },
/* 079,53 */ {
    ".....T...."
    ".........."
    ".........."
    "T........."
    "..T..T...."
    "...T......"
    ".........="
    "TT.T.TT..="
    "T........="
  , "KINGS ROAD", "" },
/* 080,53 */ {
    "T=...,...."
    ".=T...,,.."
    "T=..T.,..."
    ".=........"
    "==........"
    "=........,"
    "=........."
    ".........."
    ".........."
  , "KINGS ROAD", "" },
/* 081,53 */ {
    ".........."
    ".........."
    "...,......"
    ".....,..*."
    "......,*.."
    "......*.*."
    "...,..*.**"
    "......*.*."
    "..T*T..*.."
  , "MEADOWS", "" },
/* 082,53 */ {
    ".*...*...*"
    "*..*...*.*"
    "...*....*."
    "***......*"
    "..**....*."
    ".....*...."
    "....*....."
    "*.......*."
    "..*.**...*"
  , "MEADOWS", "" },
/* 083,53 */ {
    "*........."
    "......,..."
    "**......,."
    "*.*......,"
    ".**.....*."
    "..*.*.**.*"
    "...*..*..*"
    "...*.***.."
    ".......*.."
  , "MEADOWS", "" },
/* 084,53 */ {
    "......,..."
    ".........."
    ".........."
    ".........."
    ".........."
    ".**......."
    ".*........"
    "*......,.."
    ".........,"
  , "PLAINS", "" },
/* 085,53 */ {
    ",.,......,"
    ".........."
    ".........."
    ".....,...."
    ".........,"
    ".........."
    ".........."
    ".........."
    ".........."
  , "PLAINS", "" },
/* 086,53 */ {
    ".........."
    ".,........"
    "..,......."
    ".........."
    ".....,...."
    ".........."
    ",........."
    ",........."
    "....,....."
  , "PLAINS", "" },
/* 087,53 */ {
    ".........."
    ".........."
    "........,."
    ".........."
    ".........."
    ".........."
    ",........."
    "..,......."
    ".,........"
  , "PLAINS", "" },
/* 088,53 */ {
    "....T..T.T"
    ".....TT..T"
    ".....T.T.."
    "..,..T.TT."
    ".....T.TTT"
    "...T..T..."
    "...T...TTT"
    ".....T.TTT"
    "...T....TT"
  , "PLAINS", "" },
/* 089,53 */ {
    "TT..TTTTTT"
    ".TT.TTTTT."
    ".TTTTT..TT"
    ".T.TTTTTTT"
    ".TTTTTTTTT"
    "TTTTTTTTTT"
    "TTTTTTTTTT"
    "TTT.T.TTTT"
    ".TTT.T.TTT"
  , "OLD FOREST", "" },
/* 090,53 */ {
    "TTTTTT..TT"
    "TTTTT.TTT."
    ".TTTTTT.TT"
    "T.T.TTTTT."
    "TTTTTTTTTT"
    "TT.T.TTTT."
    ".TT.TT..T."
    "TTT.TTT..."
    "TTTTT...T."
  , "OLD FOREST", "" },
/* 091,53 */ {
    "..T.TT...."
    "T......T.."
    "TT..T.T..."
    "TTT......."
    "T..TT.TT.."
    "TTT.....T."
    "TTT..T.T.."
    ".TT.T....."
    "T.......T."
  , "PLAINS", "" },
/* 092,53 */ {
    "....,....."
    "........,."
    ".........."
    ".........,"
    ".........,"
    ".........."
    ".........."
    ".....*.*.."
    "...*......"
  , "PLAINS", "" },
/* 093,53 */ {
    ".........."
    "....,....."
    ".........."
    ".........,"
    ".........."
    "...,......"
    "....,....."
    ".,.,......"
    "..,......,"
  , "PLAINS", "" },
/* 094,53 */ {
    ".........."
    ".........."
    ".........."
    ".........."
    ".,........"
    ",........."
    ".........."
    ".,........"
    "........,."
  , "PLAINS", "" },
/* 095,53 */ {
    ".,.....,.."
    ".........."
    "..,......."
    "..,......."
    "......,..."
    ".......,.."
    ",...,.,..."
    ".....,...."
    ",........."
  , "PLAINS", "" },
/* 096,53 */ {
    ".........."
    "......*..."
    "..**...*.."
    "....*.*..."
    ".*.*.*.**."
    "......*.*."
    "....*.*..*"
    "..*.....*."
    ".,......*."
  , "MEADOWS", "" },
/* 097,53 */ {
    ".*..*..*.*"
    ".*.***..*."
    ".....*...."
    "**..*..*.*"
    ".*...*...."
    ".*.*...*.*"
    "........*."
    "**.*.**..."
    "*........*"
  , "MEADOWS", "" },
/* 098,53 */ {
    ".*........"
    ".....,...."
    ".......,.."
    "......,..."
    ",........."
    ".......,.."
    ".....,...."
    "....,....."
    "......,..."
  , "PLAINS", "" },
/* 099,53 */ {
    "........,."
    "........,."
    ".........."
    ".........."
    "......,..."
    ".........."
    "....,.,..."
    ".........."
    ".......MMM"
  , "PLAINS", "" },
/* 100,53 */ {
    "*.Rr=.Rr.*"
    "..HD=.HD.."
    "....=....."
    "...ppppS.."
    "===pppp==="
    "...pppp..."
    "..Rr=.Rr.."
    "..HD=.HD.."
    "*...=....*"
  , "DEEPMERE", "WELCOME TO DEEPMERE" },
/* 101,53 */ {
    ".=.*......"
    "*=*...**.."
    ".=.**..*.."
    ".=..*..*.*"
    "==........"
    ".......P.P"
    ".........."
    ".........."
    ".,........"
  , "MEADOWS", "" },
/* 102,53 */ {
    ".*........"
    "*....P...."
    ".*....P..."
    "...P.P...."
    "....P....."
    ".........."
    ".........."
    ".P...P...."
    "...MMMMMMM"
  , "PLAINS", "" },
/* 103,53 */ {
    "...,......"
    "..,......."
    ".........."
    "...,....MM"
    ".,....MMMM"
    ",....MMMMM"
    "..,...MMMM"
    ",...,.MMMM"
    "M....,.MMM"
  , "PLAINS", "" },
/* 104,53 */ {
    "....MMMMMM"
    "....MMMMMM"
    "..,MMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 105,53 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 106,53 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 107,53 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 108,53 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 109,53 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMM."
    "MMMMMMMM.."
    "MMMMMM.P.."
  , "GRAY PEAKS", "" },
/* 110,53 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    ".MMMMMMMMM"
    ".PMMMMMMMM"
    "P.PMMMMMMM"
  , "GRAY PEAKS", "" },
/* 111,53 */ {
    "MMMMM.P..P"
    "MMMMMP.PPP"
    "MMMMMP.PPP"
    "MMMMMPPP.P"
    "MMMMMMPPPP"
    "MMMMMMMPPP"
    "MMMMMMM..."
    "MMMMMMMMPP"
    "MMMMMMMM.P"
  , "GRAY PEAKS", "" },
/* 112,53 */ {
    "..PPPPPPPP"
    "P.P.PPPPPP"
    "PPPPPPPPPP"
    "PPPPPPPPPP"
    "P.PPPPPPPP"
    ".PPPPP..PP"
    ".PPPPPPPPP"
    "PPPP.PPPP."
    "P.PPPPP..P"
  , "PINE WOODS", "" },
/* 113,53 */ {
    ".PPPTTTTT."
    "PP.PTT..T."
    "PPPPTTTTTT"
    "PPPPTTTT.T"
    "P.PPTTTT.."
    "PP.PTT.TTT"
    "PPPT.TTTTT"
    ".PPTTT.TTT"
    "PPTTTTTTTT"
  , "OLD FOREST", "" },
/* 114,53 */ {
    "TTTT.T.TTT"
    "TTTTTTTTTT"
    "TTTTTT.TTT"
    "TTTT.TT..."
    "TTT.TTTTT."
    "T...TTTTTT"
    "TTTTTTT.TT"
    ".TTTTTTTTT"
    "T..TTTTTTT"
  , "OLD FOREST", "" },
/* 115,53 */ {
    "TTTTT=TTT."
    "T.TTT=T.TT"
    "T.T.T=TT.T"
    "TTTTS=TTTT"
    ".TTTT=TT.."
    "TTTTT=T.TT"
    "TT..T=TTT."
    "..TTT=TTTT"
    "T.TTT=T.TT"
  , "OLD FOREST", "TO WINDDALE 4N" },
/* 116,53 */ {
    ".T.TTTTTTT"
    ".TTT.TT.T."
    "T.TTTTT.TT"
    "T..TTT.T.T"
    "TTTT......"
    "TTTTTTTT.T"
    "TTT..TT.T."
    ".TTT..TT.."
    "TTT..TT.T."
  , "OLD FOREST", "" },
/* 117,53 */ {
    "TTTT......"
    "TTT..T...."
    "...T....T."
    ".T...T...,"
    "T..T...T.,"
    ".T.T......"
    "TTT......."
    "T.TT....T."
    ".....T...."
  , "PLAINS", "" },
/* 118,53 */ {
    "..,..ss~~~"
    ".....ss~~~"
    ".....ss~~~"
    ",....ss~~~"
    ".....sss~~"
    ".....sss~~"
    ".....sss~~"
    "..,..sss~~"
    "....ssss~~"
  , "PLAINS", "" },
/* 119,53 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 120,53 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 121,53 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 122,53 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 123,53 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 124,53 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 125,53 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 126,53 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 127,53 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
};
