#pragma bank 255
#include <gb/gb.h>
#include "world/world.h"
/* Only gb.h (BANKREF), not engine.h: through gbdk/emu_debug.h it adds 2 bytes of bank 0 and of RAM to every file
   that includes it, and 96 of these files overflowed bank 0.
   PLAY GAME 2 world row 80: screens x = 0..127 at y = 80, 128 bytes each = one full 16 KB ROM bank.
   Per screen: 9 rows of 10 metatile chars (legend: ow_metatiles in assets/tilesets/ts_overworld.c),
   the HUD name and the text of its sign ("" = no sign). Format: assets/world/world.h */
BANKREF(world_r80)
const wscreen_t world_r80[WORLD_W] = {
/* 000,80 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 001,80 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 002,80 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 003,80 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 004,80 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 005,80 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 006,80 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 007,80 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 008,80 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 009,80 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 010,80 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 011,80 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 012,80 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 013,80 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 014,80 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 015,80 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 016,80 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 017,80 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 018,80 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 019,80 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 020,80 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 021,80 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 022,80 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 023,80 */ {
    "~ssscsssss"
    "~~ssssssss"
    "~~ssssssss"
    "~~~sssssss"
    "~~~~ssssss"
    "~~~~ssssss"
    "~~~~~sssss"
    "~~~~~~ssss"
    "~~~~~~~sss"
  , "COAST", "" },
/* 024,80 */ {
    "ssssssssss"
    "scssssssss"
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 025,80 */ {
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 026,80 */ {
    "sssscsssss"
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssscssssss"
  , "DUNE WASTES", "" },
/* 027,80 */ {
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 028,80 */ {
    "ssssssssMM"
    "sssssssssM"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 029,80 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "sMMMMMMMMM"
    "sssMMMMMMM"
    "ssssMMMMMM"
    "sssssssMMM"
    "ssssssssss"
    "ssssssssss"
  , "GRAY PEAKS", "" },
/* 030,80 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "sMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 031,80 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 032,80 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 033,80 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMs"
  , "GRAY PEAKS", "" },
/* 034,80 */ {
    "MMM=ssssss"
    "MMM=ssssss"
    "MMM=ssssss"
    "MMs=ssssss"
    "MMs=ssssss"
    "Mss=ssssss"
    "sss=ssssss"
    "sss=ssssss"
    "sss=ssssss"
  , "DUNE WASTES", "" },
/* 035,80 */ {
    "ssssssssMM"
    "ssssssssMM"
    "sssssssMMM"
    "ssssssMMMM"
    "ssssscMMMM"
    "sssssMMMMM"
    "sssssMMMMM"
    "cssssMMMMM"
    "ssssMMMMMM"
  , "GRAY PEAKS", "" },
/* 036,80 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMs"
    "MMMMMsssss"
  , "GRAY PEAKS", "" },
/* 037,80 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMs"
    "MMMMMMMsss"
    "MMMMMMssss"
    "Msscssssss"
    "ssssssssss"
    "ssssssssss"
  , "GRAY PEAKS", "" },
/* 038,80 */ {
    "MMMMMMMMss"
    "MMMMMMssss"
    "MMMMssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "ssssssscss"
  , "DUNE WASTES", "" },
/* 039,80 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 040,80 */ {
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 041,80 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 042,80 */ {
    "ssssssssss"
    "sssscsssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 043,80 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 044,80 */ {
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "scsssscsss"
  , "DUNE WASTES", "" },
/* 045,80 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 046,80 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssscssssc"
    "sssssssssc"
  , "DUNE WASTES", "" },
/* 047,80 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 048,80 */ {
    "ssssssssss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 049,80 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "sscsssssss"
    "sssssssssc"
  , "DUNE WASTES", "" },
/* 050,80 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 051,80 */ {
    "scssssssss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "csssscssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 052,80 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "sssscsssss"
  , "DUNE WASTES", "" },
/* 053,80 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssscsssscs"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssscssssss"
  , "DUNE WASTES", "" },
/* 054,80 */ {
    "scssssssss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssscss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 055,80 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 056,80 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssssss~"
    "ssss~ssss~"
    "ssss~~sss~"
  , "DUNE WASTES", "" },
/* 057,80 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 058,80 */ {
    "==ssssssss"
    "~=ssssssss"
    "~=sscsssss"
    "~==scsssss"
    "~s==ssssss"
    "~~s=ssssss"
    "~~s=ssssss"
    "~~s=ssssss"
    "~~~=ssssss"
  , "DUNE WASTES", "" },
/* 059,80 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 060,80 */ {
    "ssssssssss"
    "sscsssscss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 061,80 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 062,80 */ {
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 063,80 */ {
    "csssssssss"
    "csssssssss"
    "ssssssscss"
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 064,80 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 065,80 */ {
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 066,80 */ {
    "ssss=sssss"
    "csss=sssss"
    "sscs=sssss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
  , "DUNE WASTES", "" },
/* 067,80 */ {
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 068,80 */ {
    "ssscssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
  , "DUNE WASTES", "" },
/* 069,80 */ {
    "ssssssssss"
    "sssscsssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 070,80 */ {
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 071,80 */ {
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 072,80 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 073,80 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 074,80 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
  , "DUNE WASTES", "" },
/* 075,80 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 076,80 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssssssc"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 077,80 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
  , "DUNE WASTES", "" },
/* 078,80 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 079,80 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "sssssssssc"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 080,80 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
  , "DUNE WASTES", "" },
/* 081,80 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 082,80 */ {
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "sssssssssc"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 083,80 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 084,80 */ {
    "sssssss=ss"
    "ssscsss=ss"
    "sssssss=ss"
    "sssssss=ss"
    "sssssss=ss"
    "ssssscs=ss"
    "sssssss=ss"
    "sssssss=ss"
    "sssssss=ss"
  , "DUNE WASTES", "" },
/* 085,80 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 086,80 */ {
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "csssscssss"
  , "DUNE WASTES", "" },
/* 087,80 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 088,80 */ {
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssscsssscs"
    "sssssssscs"
  , "DUNE WASTES", "" },
/* 089,80 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 090,80 */ {
    "ssssssssss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 091,80 */ {
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "scssssssss"
    "sssssssscs"
  , "DUNE WASTES", "" },
/* 092,80 */ {
    "sssssss==s"
    "ssssssss=="
    "sssssssss="
    "scsssssss="
    "sssssssss="
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 093,80 */ {
    "csssssssss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
    "===sssssss"
    "ss=scsssss"
    "ss=scsssss"
    "ss===sssss"
    "ssss=sssss"
  , "DUNE WASTES", "" },
/* 094,80 */ {
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "ssscssssss"
  , "DUNE WASTES", "" },
/* 095,80 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sscsssscss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
  , "DUNE WASTES", "" },
/* 096,80 */ {
    "c=ssssssss"
    "s=ssssscss"
    "s=ssssssss"
    "s=ssssssss"
    "s=ssssssss"
    "==ssssssss"
    "=ssscsssss"
    "=ssssscsss"
    "=sssssssss"
  , "DUNE WASTES", "" },
/* 097,80 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 098,80 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "csssssssss"
    "ssssssscss"
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 099,80 */ {
    "csssssssss"
    "ssssssssss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 100,80 */ {
    "ssssssssss"
    "ssssssssss"
    "ssscssssss"
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 101,80 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "sscsssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 102,80 */ {
    "ssssssssss"
    "scsssscsss"
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 103,80 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssscssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 104,80 */ {
    "sssscssssc"
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 105,80 */ {
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 106,80 */ {
    "sssssssss="
    "sssssssss="
    "sssssssss="
    "ssssssscs="
    "sssssssss="
    "ssssssss=="
    "ssssssss=s"
    "ssssssss=s"
    "sssssss==s"
  , "DUNE WASTES", "" },
/* 107,80 */ {
    "sscsssssss"
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 108,80 */ {
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 109,80 */ {
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 110,80 */ {
    "sscsssssss"
    "sssscsssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
  , "DUNE WASTES", "" },
/* 111,80 */ {
    "ssssssssss"
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 112,80 */ {
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 113,80 */ {
    "ssss=scsss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
  , "DUNE WASTES", "" },
/* 114,80 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 115,80 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 116,80 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
  , "DUNE WASTES", "" },
/* 117,80 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 118,80 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssssscs"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 119,80 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssscsssss~"
    "ssssssss~~"
    "sssssss~~~"
    "sssssss~~~"
    "ssssss~~~~"
  , "DUNE WASTES", "" },
/* 120,80 */ {
    "ss~~~~~~~~"
    "s~~~~~~~~~"
    "s~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 121,80 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 122,80 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 123,80 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 124,80 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 125,80 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 126,80 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 127,80 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
};
