#pragma bank 255
#include <gb/gb.h>
#include "world/world.h"
/* Only gb.h (BANKREF), not engine.h: through gbdk/emu_debug.h it adds 2 bytes of bank 0 and of RAM to every file
   that includes it, and 96 of these files overflowed bank 0.
   PLAY GAME 2 world row 73: screens x = 0..127 at y = 73, 128 bytes each = one full 16 KB ROM bank.
   Per screen: 9 rows of 10 metatile chars (legend: ow_metatiles in assets/tilesets/ts_overworld.c),
   the HUD name and the text of its sign ("" = no sign). Format: assets/world/world.h */
BANKREF(world_r73)
const wscreen_t world_r73[WORLD_W] = {
/* 000,73 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 001,73 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 002,73 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 003,73 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 004,73 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 005,73 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 006,73 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 007,73 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 008,73 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 009,73 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 010,73 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 011,73 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 012,73 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 013,73 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 014,73 */ {
    "~~~~~~ssss"
    "~~~~~sssss"
    "~~~~~sssss"
    "~~~~ssssss"
    "~~~~ssssss"
    "~~~sssssss"
    "~~~sssssss"
    "~~ssssssss"
    "~~ssssssss"
  , "COAST", "" },
/* 015,73 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssss~~ssss"
    "ss~~~~ssss"
  , "DUNE WASTES", "" },
/* 016,73 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 017,73 */ {
    "s....sssss"
    "sss..sssss"
    "ssssssssss"
    "ssssssss~~"
    "ssssss~~~~"
    "sssss~~~~~"
    "ssss~~~~~~"
    "ssss~~~~~~"
    "ssss~~~~~~"
  , "DUNE WASTES", "" },
/* 018,73 */ {
    "ss~~~~~~~~"
    "s~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 019,73 */ {
    "~s=s~~~~ss"
    "ss=ss~~==="
    "ss======ss"
    "~sssssssss"
    "~~sssssss."
    "~~~~sssss,"
    "~~~~sssss."
    "~~~~ssss.."
    "~~~~ssss,."
  , "DUNE WASTES", "" },
/* 020,73 */ {
    "ss..ssssss"
    "=========="
    "......ssss"
    ".......sss"
    ".....sssss"
    "....ssssss"
    "...ssscsss"
    ".sssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 021,73 */ {
    "ssssssssss"
    "=========="
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssscssssc"
  , "DUNE WASTES", "" },
/* 022,73 */ {
    "csssssssss"
    "=========="
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 023,73 */ {
    "ssss......"
    "=========="
    "ssssssssS."
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssscss"
    "ssssssssss"
  , "DUNE WASTES", "TO WINDTON 3S 2E" },
/* 024,73 */ {
    ".....T.T.."
    "=========="
    ".......T.T"
    ".....T...."
    "s..,.....T"
    "sss......."
    "sssss....."
    "sscsss,..."
    "sscsssss.."
  , "KINGS ROAD", "" },
/* 025,73 */ {
    ".T.=....T."
    "====......"
    "..T=T...T."
    "...=.....T"
    ".TT=T....."
    ".T.=......"
    "...=.TT.TT"
    "...=T....T"
    "..T=T.TT.."
  , "KINGS ROAD", "" },
/* 026,73 */ {
    "T......TMM"
    ".T.....MMM"
    "T......MMM"
    "......MMMM"
    "....MMMMMM"
    "T..MMMMMMM"
    "T.MMMMMMMM"
    ".MMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 027,73 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 028,73 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 029,73 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 030,73 */ {
    "MMM.TTT..."
    "MMM..TT.T."
    "MMMTT.TTTT"
    "MM..T.TTTT"
    "MMT.TTTTTT"
    "MMTT.TTTTT"
    "MMTT..TTT."
    "MM.TTTT..."
    "MMTTTTTTTT"
  , "OLD FOREST", "" },
/* 031,73 */ {
    ".TTTT.TT.T"
    ".TTTTT..T."
    ".T.TTTTTTT"
    "TTTTTTT.T."
    "TTTTTTT.T."
    ".TTTT.TTTT"
    "TTTTT..TT."
    "TTTTTTTT.."
    "TTT.TTTT.."
  , "OLD FOREST", "" },
/* 032,73 */ {
    ".T..=...,."
    "TT.T=....."
    "T...=....."
    ".T..=,...,"
    "...T=....."
    ".T..=....."
    "..TT=....."
    "T.T.=....,"
    ".T..=....."
  , "KINGS ROAD", "" },
/* 033,73 */ {
    ".....,...."
    "....,....."
    "......,..."
    "....,...,."
    "....,....,"
    ".........."
    ".........,"
    ".........."
    ".,........"
  , "PLAINS", "" },
/* 034,73 */ {
    "....,MMMMM"
    ".....MMMMM"
    ".....MMMMM"
    ".....MMMMM"
    "....,MMMMM"
    ".,...MMMMM"
    "...,.MMMMM"
    ".....MMMMM"
    ".....MMMMM"
  , "GRAY PEAKS", "" },
/* 035,73 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 036,73 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 037,73 */ {
    "MMMMMMM..."
    "MMMMM,...."
    "MMMM......"
    "MMMM......"
    "MMMM......"
    "MMMM.,...."
    "MMMM...,.."
    "MMMM....,."
    "MMMM......"
  , "GRAY PEAKS", "" },
/* 038,73 */ {
    "..,....MMM"
    ",...,....M"
    ",....,...."
    ".......,.."
    ".....,...,"
    ".........."
    ".........."
    ".........."
    ".........."
  , "PLAINS", "" },
/* 039,73 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    ",MMMMMMMMM"
    ".,,MMMMMMM"
    ".,..MMMMMM"
    "......MMMM"
    ".........."
    "....,....."
    "........**"
  , "GRAY PEAKS", "" },
/* 040,73 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    ".**MMMMMMM"
    "**.*.MMMMM"
    ".*.**...MM"
  , "GRAY PEAKS", "" },
/* 041,73 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMsssss"
    "MM..ssssss"
  , "GRAY PEAKS", "" },
/* 042,73 */ {
    "MMMMMMMMss"
    "MMMMMMMMss"
    "MMMMMMMsss"
    "MMMMMMMsss"
    "MMMMMMssss"
    "MMMMMsssss"
    "MMMMssssss"
    "ssssssssss"
    "ssssssssss"
  , "GRAY PEAKS", "" },
/* 043,73 */ {
    "ssssssssss"
    "ssscssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 044,73 */ {
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 045,73 */ {
    "sssssscsss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
  , "DUNE WASTES", "" },
/* 046,73 */ {
    "ssssssssss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 047,73 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssssscs"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 048,73 */ {
    "scssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 049,73 */ {
    "csssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 050,73 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 051,73 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssssssc"
  , "DUNE WASTES", "" },
/* 052,73 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 053,73 */ {
    "*.Rr=.Rr.*"
    "..HD=.HD.."
    "....=....."
    "...ppppS.."
    "===pppp==="
    "...pppp..."
    "..Rr=.Rr.."
    "..HD=.HD.."
    "*...=....*"
  , "COLDGATE", "WELCOME TO COLDGATE" },
/* 054,73 */ {
    "=sssssssss"
    "=sssssssss"
    "=sssssssss"
    "=sssssssss"
    "=sssssscss"
    "==ssssssss"
    "s=ssssssss"
    "s=csssssss"
    "s=sssssssc"
  , "DUNE WASTES", "" },
/* 055,73 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 056,73 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 057,73 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "sssssssssc"
  , "DUNE WASTES", "" },
/* 058,73 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 059,73 */ {
    "ssssssssss"
    "ssssssssss"
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 060,73 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 061,73 */ {
    "s........."
    "sss...,..."
    "ssss....,."
    "sssss..,.."
    "scssss...."
    "sssssss.,."
    "ssssssss.."
    "sssssssss*"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 062,73 */ {
    ".........,"
    ".........,"
    ".........."
    ".**..*...."
    "*.*..*.*.."
    "*..*......"
    "..*.**.*.."
    "..*.*....."
    "*.......**"
  , "MEADOWS", "" },
/* 063,73 */ {
    ".........T"
    ".........."
    "...,......"
    "....,....."
    ".,.,......"
    "..,......,"
    "........,."
    ".........."
    "...,....T."
  , "PLAINS", "" },
/* 064,73 */ {
    "....TT.T.T"
    ".T.T...TT."
    "T.T.TTT.T."
    "...T.TT.T."
    ".T.T..T.TT"
    ".....T.TT."
    "..T..T.T.T"
    "T.TT....TT"
    "..T..T..TT"
  , "OLD FOREST", "" },
/* 065,73 */ {
    ".TTTT.TTTT"
    ".T..TTTTTT"
    "TTT....TTT"
    "T...TTTT.."
    "T....TT.T."
    "TTTTT.TTTT"
    "T...T.TTTT"
    ".TT.TTT.TT"
    "T.TT.TTTTT"
  , "OLD FOREST", "" },
/* 066,73 */ {
    "TTTTT.TT.."
    "TT.T.TTTTT"
    "TTT.T.T.TT"
    "TTT.T.TTTT"
    ".TTTTT..T."
    ".T.TTT.TTT"
    "TTTTTTT.TT"
    ".T.TTTT.T."
    ".TT...TTTT"
  , "OLD FOREST", "" },
/* 067,73 */ {
    "TT.T=..T.T"
    "TT.T=T...."
    ".TTT=S.TTT"
    ".TTT=...T."
    "TT.T=TTT.T"
    "T.TT=..T.s"
    "TTT.=T.ssc"
    "TTTT=sssss"
    ".sss=sssss"
  , "OLD FOREST", "TO GOLDHOLM 2N" },
/* 068,73 */ {
    "TTTTT.T.TT"
    "TTTT.T..ss"
    ".....Tscss"
    ".T.sssssss"
    "Tsssssssss"
    "ssssssssss"
    "sssscsssss"
    "sssscsssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 069,73 */ {
    "TTT.ssssss"
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
  , "DUNE WASTES", "" },
/* 070,73 */ {
    "ss.PP.P.P."
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sscsssscss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 071,73 */ {
    "ssssssssss"
    "csssssssss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
    "sssssscsss"
  , "DUNE WASTES", "" },
/* 072,73 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
  , "DUNE WASTES", "" },
/* 073,73 */ {
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "csssssssss"
    "ssssssscss"
    "sssssssssc"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 074,73 */ {
    "ssssssssss"
    "csssssssss"
    "ssssssssss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssssscs"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 075,73 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssscssssss"
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 076,73 */ {
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "sscsssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 077,73 */ {
    "ssssssssss"
    "ssssssssss"
    "scsssscsss"
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 078,73 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssscssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 079,73 */ {
    "ssssssssss"
    "sssscssssc"
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 080,73 */ {
    "sssss=ssss"
    "sssss=ssss"
    "sssss=ssss"
    "sssss=csss"
    "sssss===cs"
    "sssssss=ss"
    "sssssss=ss"
    "sssssss=ss"
    "sssssss=ss"
  , "DUNE WASTES", "" },
/* 081,73 */ {
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 082,73 */ {
    "ssc=====ss"
    "ssc=ssssss"
    "sss=sssssc"
    "sss=ssssss"
    "ss==ssssss"
    "ss=sssssss"
    "===sssssss"
    "=sssssssss"
    "=sssssssss"
  , "DUNE WASTES", "" },
/* 083,73 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 084,73 */ {
    "ssssscss.."
    "sssssssss."
    "ssssssssss"
    "csssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 085,73 */ {
    ",....*.*.*"
    "..,...**.."
    ",...,.,..."
    "s........."
    "sss......."
    "ssss.....,"
    "ssssss...."
    "ssssssss.."
    "ssssssssss"
  , "PLAINS", "" },
/* 086,73 */ {
    "*......P.."
    ".........."
    "...P..P..P"
    ".....P..P."
    "......PP.."
    "......P.P."
    "...P..P.PP"
    "......P.PP"
    "..PPP..P.."
  , "PLAINS", "" },
/* 087,73 */ {
    ".P..PP...P"
    "P..PP..P.P"
    ".P.P...PP."
    "PPP...PP.P"
    "P.PP..PPPP"
    "....PP...P"
    "..P.P..P.."
    "P.......P."
    ".PP.PP...P"
  , "PINE WOODS", "" },
/* 088,73 */ {
    "P...P....."
    ".P..PPPPPP"
    "PP.PPP..PP"
    "PPP.PPP..P"
    ".PPP.P..PP"
    "..P.PPPP.P"
    "PP.P..PPPP"
    ".P.PPPPPP."
    "P.P.P.PP.P"
  , "PINE WOODS", "" },
/* 089,73 */ {
    "...P.PPP.."
    "P.P.P.P..."
    ".PPPPP...P"
    "P..P.PP..P"
    ".P...P.PP."
    "PPP..P.P.."
    ".PPP.P...."
    "P...PPPPP."
    ".P.P.....P"
  , "PINE WOODS", "" },
/* 090,73 */ {
    "P.P.P.PPPP"
    ".P.PP.PP.."
    "P.PP.P.PPP"
    ".PP.PPP.P."
    "..P..P.PPP"
    "P..PP.P..P"
    ".P..P.PPPP"
    "..PP.P.P.P"
    ".P...PP..P"
  , "PINE WOODS", "" },
/* 091,73 */ {
    "P.T......T"
    ".P..T.TT.."
    "..TT.....*"
    ".TT.T....."
    "P.T.TT...."
    "..T.T....."
    "P.......*."
    "P........."
    "..P.T....s"
  , "PLAINS", "" },
/* 092,73 */ {
    "....T.*sss"
    ".....Tssss"
    "....Tsssss"
    ".T..ssssss"
    "*..sssssss"
    "..ssssssss"
    "Tsssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 093,73 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssssscs"
  , "DUNE WASTES", "" },
/* 094,73 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 095,73 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 096,73 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "sssssssscs"
  , "DUNE WASTES", "" },
/* 097,73 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 098,73 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 099,73 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "sssssssscs"
  , "DUNE WASTES", "" },
/* 100,73 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 101,73 */ {
    "sMMMMMMMMM"
    "ssMMMMMMMM"
    "sscMMMMMMM"
    "sssMMMMMMM"
    "sssMMMMMMM"
    "sssMMMMMMM"
    "ssMMMMMMMM"
    "ssMMMMMMMM"
    "ssMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 102,73 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 103,73 */ {
    "MssMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 104,73 */ {
    "MMMMMMMMss"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 105,73 */ {
    "sssss=sscs"
    "sssss=ssss"
    "Mssss=ssss"
    "MMscs=ssss"
    "MMMss=ssss"
    "MMMMs==sss"
    "MMMMss=sss"
    "MMMMMs=sss"
    "MMMMMs=css"
  , "DUNE WASTES", "" },
/* 106,73 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 107,73 */ {
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 108,73 */ {
    "ssssss...."
    "sssssssss."
    "ssssssssss"
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "csssssssss"
  , "DUNE WASTES", "" },
/* 109,73 */ {
    ".MMMMMMMMM"
    "..MMMMMMMM"
    "ssMMMMMMMM"
    "sssMMMMMMM"
    "cssMMMMMMM"
    "ssMMMMMMMM"
    "ssMMMMMMMM"
    "sMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 110,73 */ {
    "MMM..,...."
    "MMM......."
    "MMM...,..."
    "MMM.,....."
    "MMMsss...."
    "MMMMssssss"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 111,73 */ {
    ".........."
    ".....,...,"
    ".........."
    "...,.,...."
    ".....MM..."
    "...MMMMM.."
    "MMMMMMMMM."
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 112,73 */ {
    "..,..MMMMM"
    ".,...MMMMM"
    ",....MMMMM"
    ".....MMMMM"
    "....MMMMMM"
    ".,..MMMMMM"
    "..MMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 113,73 */ {
    "MMM.ssssss"
    "MMMsssssss"
    "MMMMsscsss"
    "MMMMssssss"
    "MMMMsssssM"
    "MMMMssssMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 114,73 */ {
    "sMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 115,73 */ {
    "MMMsssssss"
    "MMMMsssssc"
    "MMMMssssss"
    "MMMMMsssss"
    "MMMMMMssss"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 116,73 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
    "MMssssssss"
    "MMMsssMMMs"
    "MMMMMMMMMs"
  , "DUNE WASTES", "" },
/* 117,73 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "sscsssssss"
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 118,73 */ {
    "sscsssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 119,73 */ {
    "ssss=sssss"
    "ssss=sssss"
    "csss=cssss"
    "ssss=cssss"
    "ssss=sssss"
    "ssss=sssss"
    "csss=sssss"
    "ssss=sssss"
    "ssss=sssss"
  , "DUNE WASTES", "" },
/* 120,73 */ {
    "sssssssss~"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "sssscsssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 121,73 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 122,73 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 123,73 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 124,73 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 125,73 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 126,73 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 127,73 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
};
