#pragma bank 255
#include <gb/gb.h>
#include "world/world.h"
/* Only gb.h (BANKREF), not engine.h: through gbdk/emu_debug.h it adds 2 bytes of bank 0 and of RAM to every file
   that includes it, and 96 of these files overflowed bank 0.
   PLAY GAME 2 world row 82: screens x = 0..127 at y = 82, 128 bytes each = one full 16 KB ROM bank.
   Per screen: 9 rows of 10 metatile chars (legend: ow_metatiles in assets/tilesets/ts_overworld.c),
   the HUD name and the text of its sign ("" = no sign). Format: assets/world/world.h */
BANKREF(world_r82)
const wscreen_t world_r82[WORLD_W] = {
/* 000,82 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 001,82 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 002,82 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 003,82 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 004,82 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 005,82 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 006,82 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 007,82 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 008,82 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 009,82 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 010,82 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 011,82 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 012,82 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 013,82 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 014,82 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 015,82 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 016,82 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 017,82 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 018,82 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 019,82 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 020,82 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 021,82 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 022,82 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 023,82 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 024,82 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 025,82 */ {
    "ssssssssss"
    "~sssssssss"
    "~~ssssscss"
    "~~~sssssss"
    "~~~~ssssss"
    "~~~~~sssss"
    "~~~~~~ssss"
    "~~~~~~~sss"
    "~~~~~~~~~~"
  , "COAST", "" },
/* 026,82 */ {
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssssscs"
  , "DUNE WASTES", "" },
/* 027,82 */ {
    "ssssssssss"
    "scssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 028,82 */ {
    "ssssssssss"
    "csssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 029,82 */ {
    "sssscsssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 030,82 */ {
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 031,82 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 032,82 */ {
    "sssssssssM"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssss===="
    "ssssss=sss"
    "ssssss=sss"
  , "DUNE WASTES", "" },
/* 033,82 */ {
    "MMMMMMMMMM"
    "sMMMMMMMMM"
    "sssMMMMMMM"
    "ssssMMMMss"
    "ssssssMsss"
    "ssssssscss"
    "=========="
    "ssssssssss"
    "sscsssssss"
  , "GRAY PEAKS", "" },
/* 034,82 */ {
    "MMMs=sssss"
    "MMss=sssss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
    "=====sssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 035,82 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 036,82 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
  , "DUNE WASTES", "" },
/* 037,82 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 038,82 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 039,82 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
  , "DUNE WASTES", "" },
/* 040,82 */ {
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 041,82 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 042,82 */ {
    "ssssssssss"
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 043,82 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 044,82 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
  , "DUNE WASTES", "" },
/* 045,82 */ {
    "sscsssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
  , "DUNE WASTES", "" },
/* 046,82 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "ssssssssss"
    "sssssssssc"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 047,82 */ {
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
    "sssscsssss"
  , "DUNE WASTES", "" },
/* 048,82 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 049,82 */ {
    "ssssssssss"
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sscsssscss"
    "ssssssscss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 050,82 */ {
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
  , "DUNE WASTES", "" },
/* 051,82 */ {
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 052,82 */ {
    "ssssssssss"
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "csssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 053,82 */ {
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "ssssssssss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssssscs"
  , "DUNE WASTES", "" },
/* 054,82 */ {
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssscssssss"
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 055,82 */ {
    "ssssssssss"
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "sscsssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 056,82 */ {
    "sssssss~~~"
    "ssssssss~~"
    "ssssssss~~"
    "scssssss~~"
    "ssssssss~~"
    "ssssssss~~"
    "ssssssss~~"
    "scssssss~~"
    "sssssss~~~"
  , "DUNE WASTES", "" },
/* 057,82 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 058,82 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 059,82 */ {
    "~~~~~~~~~s"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 060,82 */ {
    "ssssssssss"
    "~~~~~~ssss"
    "~~~~~~~~ss"
    "~~~~~~~~~s"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "COAST", "" },
/* 061,82 */ {
    "ssssssssss"
    "sscsssssss"
    "sscsssssss"
    "sssssssssc"
    "ssssssssss"
    "~sssssssss"
    "~sssssssss"
    "~sssssssss"
    "~sssssssss"
  , "DUNE WASTES", "" },
/* 062,82 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 063,82 */ {
    "csssscssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 064,82 */ {
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "sssscsssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 065,82 */ {
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 066,82 */ {
    "ssss=sssss"
    "ssss=cssss"
    "ssss=sscss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
  , "DUNE WASTES", "" },
/* 067,82 */ {
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 068,82 */ {
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssscss"
  , "DUNE WASTES", "" },
/* 069,82 */ {
    "ssssssssss"
    "cssssssssc"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 070,82 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 071,82 */ {
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 072,82 */ {
    "sscsssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 073,82 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 074,82 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 075,82 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
  , "DUNE WASTES", "" },
/* 076,82 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 077,82 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 078,82 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
  , "DUNE WASTES", "" },
/* 079,82 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 080,82 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 081,82 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
  , "DUNE WASTES", "" },
/* 082,82 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 083,82 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 084,82 */ {
    "sss==sssss"
    "ss==sssscs"
    "ss=sssssss"
    "ss=sssssss"
    "ss=cssssss"
    "ss=sssssss"
    "s==sssssss"
    "==ssssssss"
    "=sssssssss"
  , "DUNE WASTES", "" },
/* 085,82 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 086,82 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
  , "DUNE WASTES", "" },
/* 087,82 */ {
    "scssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
  , "DUNE WASTES", "" },
/* 088,82 */ {
    "ssssssssss"
    "ssssssssss"
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "ssssssssss"
    "sssssssscs"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 089,82 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssscssssss"
    "ssscssssss"
  , "DUNE WASTES", "" },
/* 090,82 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 091,82 */ {
    "ssssssssss"
    "sscsssssss"
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "scsssscsss"
    "sssssscsss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 092,82 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssscssssss"
  , "DUNE WASTES", "" },
/* 093,82 */ {
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssscssssc"
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 094,82 */ {
    "ss==ssssss"
    "ssc=ssssss"
    "sss=sssssc"
    "sss==sssss"
    "ssss======"
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
    "sssssssscs"
  , "DUNE WASTES", "" },
/* 095,82 */ {
    "*.Rr=.Rr.*"
    "..HD=.HD.."
    "....=....."
    "...ppppS.."
    "===pppp==="
    "...pppp..."
    "..Rr=.Rr.."
    "..HD=.HD.."
    "*...=....*"
  , "GOLDBURY", "WELCOME TO GOLDBURY" },
/* 096,82 */ {
    "=sssscssss"
    "=sssssssss"
    "=sssssssss"
    "=sssssssss"
    "=scsssssss"
    "=scsssssss"
    "=======ssc"
    "ssssss===s"
    "ssssssss=="
  , "DUNE WASTES", "" },
/* 097,82 */ {
    "ssssssssss"
    "sscsssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "=========="
  , "DUNE WASTES", "" },
/* 098,82 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "csssscssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "=========="
  , "DUNE WASTES", "" },
/* 099,82 */ {
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "sssscsssss"
    "ssssssssss"
    "=========="
  , "DUNE WASTES", "" },
/* 100,82 */ {
    "ssssssssss"
    "ssssssssss"
    "ssscsssscs"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssscssssss"
    "ssssssssss"
    "=========="
  , "DUNE WASTES", "" },
/* 101,82 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
    "=========="
  , "DUNE WASTES", "" },
/* 102,82 */ {
    "ssssssssss"
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
    "=========="
  , "DUNE WASTES", "" },
/* 103,82 */ {
    "ssssssssss"
    "scssssssss"
    "scssssssss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "=========="
  , "DUNE WASTES", "" },
/* 104,82 */ {
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "cssssssssc"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "=========="
  , "DUNE WASTES", "" },
/* 105,82 */ {
    "sssscsssss"
    "sssscsssss"
    "sssssssss="
    "sssssssss="
    "ssssssss=="
    "ssssssss=s"
    "ssssssss=s"
    "=========s"
    "=sssssssss"
  , "DUNE WASTES", "" },
/* 106,82 */ {
    "=sssssssss"
    "=sssssssss"
    "=cssssssss"
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 107,82 */ {
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 108,82 */ {
    "ssssssssss"
    "sssscsssss"
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 109,82 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 110,82 */ {
    "ssssssscss"
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
  , "DUNE WASTES", "" },
/* 111,82 */ {
    "ssssssssss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 112,82 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssssssc"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 113,82 */ {
    "sscs=sssss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
    "ssss=sssss"
  , "DUNE WASTES", "" },
/* 114,82 */ {
    "scssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 115,82 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 116,82 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 117,82 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
  , "DUNE WASTES", "" },
/* 118,82 */ {
    "sssssss~~~"
    "sssssss~~~"
    "ssssss~~~~"
    "ssssss~~~~"
    "sssss~~~~~"
    "ssss~~~~~~"
    "ssss~~~~~~"
    "sss~~~~~~~"
    "ss~~~~~~~~"
  , "COAST", "" },
/* 119,82 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 120,82 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 121,82 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 122,82 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 123,82 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 124,82 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 125,82 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 126,82 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 127,82 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
};
