#pragma bank 255
#include <gb/gb.h>
#include "world/world.h"
/* Only gb.h (BANKREF), not engine.h: through gbdk/emu_debug.h it adds 2 bytes of bank 0 and of RAM to every file
   that includes it, and 96 of these files overflowed bank 0.
   PLAY GAME 2 world row 71: screens x = 0..127 at y = 71, 128 bytes each = one full 16 KB ROM bank.
   Per screen: 9 rows of 10 metatile chars (legend: ow_metatiles in assets/tilesets/ts_overworld.c),
   the HUD name and the text of its sign ("" = no sign). Format: assets/world/world.h */
BANKREF(world_r71)
const wscreen_t world_r71[WORLD_W] = {
/* 000,71 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 001,71 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 002,71 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 003,71 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 004,71 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 005,71 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 006,71 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 007,71 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 008,71 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 009,71 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 010,71 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 011,71 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 012,71 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 013,71 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 014,71 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~s"
    "~~~~~~~~~s"
    "~~~~~~~~ss"
    "~~~~~~~~ss"
    "~~~~~~~~ss"
    "~~~~~~~~ss"
  , "COAST", "" },
/* 015,71 */ {
    "~~ssss..,*"
    "~ssss....."
    "ssss.....,"
    "sss......,"
    "ss........"
    "s........."
    "s......,.."
    "s........."
    "s....,.,.."
  , "PLAINS", "" },
/* 016,71 */ {
    ".*.**....*"
    ".*.*.*...."
    "..*....*.*"
    ".........."
    ".*.*.*...."
    "....*....."
    ".*.*......"
    "..*......,"
    "......*.,."
  , "MEADOWS", "" },
/* 017,71 */ {
    "........*."
    "...*....*."
    "*...*....."
    ".*.*...**."
    ",.*.**...."
    ".........."
    ".,........"
    "........,."
    ".........."
  , "MEADOWS", "" },
/* 018,71 */ {
    ".*..*.*.*."
    "*.,..*...."
    "..,......."
    "......,..."
    ".......,.."
    ",...,.,..."
    ".....,...."
    ",........."
    ".........."
  , "PLAINS", "" },
/* 019,71 */ {
    "ss=s~~~~~~"
    "ss=s~~~~~~"
    "ss=s~~~~~~"
    "ss=s~~~~~~"
    "ss=s~~~~~~"
    ".s=ss~~~~~"
    ".s=ss~~~~~"
    ".,=ss~~~~~"
    "..=ss~~~~~"
  , "COAST", "" },
/* 020,71 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 021,71 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~s"
    "~~~~~~~~ss"
  , "SEA", "" },
/* 022,71 */ {
    "~~~~~ss.,."
    "~~~~ss...."
    "~~~sss...."
    "~~sss.*..."
    "~sss......"
    "~sss*.*.**"
    "sss*......"
    "sss....**."
    "ss....*..."
  , "PLAINS", "" },
/* 023,71 */ {
    ".........."
    "..,......,"
    "...,......"
    ",.,......."
    ".,......,."
    ".......,.."
    ".........,"
    "..,....,.."
    ".......,.."
  , "PLAINS", "" },
/* 024,71 */ {
    ",........."
    ".........."
    ".........,"
    ",........."
    ".......,.,"
    ".........."
    ".........."
    ".T........"
    "..,....,.."
  , "PLAINS", "" },
/* 025,71 */ {
    "....=,...."
    "...S=.,..."
    "...,=,...."
    "....=....."
    "....=....."
    "....=....."
    ".,..=,...."
    "....=....."
    "....=....."
  , "KINGS ROAD", "TO HAWKHAVEN 1N" },
/* 026,71 */ {
    "..,......."
    ".....T.T.."
    "...T....T."
    ".,.....T.T"
    ",........T"
    "..,......."
    ",...T....."
    ",....T...."
    ".......T.."
  , "PLAINS", "" },
/* 027,71 */ {
    "T...MMMMMM"
    "T.T.MMMMMM"
    "....MMMMMM"
    "T.T.MMMMMM"
    "...MMMMMMM"
    "...MMMMMMM"
    "..MMMMMMMM"
    "T.MMMMMMMM"
    ".TMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 028,71 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 029,71 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 030,71 */ {
    "MMMMM....,"
    "MMMMM..,.."
    "MMMMM.,..."
    "MMMMM...T."
    "MMMMM.T..."
    "MMMMM.T..."
    "MMMMM....T"
    "MMMMM...T."
    "MMMMM..T.T"
  , "GRAY PEAKS", "" },
/* 031,71 */ {
    ".........."
    "......,.,."
    ".........."
    ".........."
    "T........."
    ".T....T..."
    "...T...TT."
    ".T...T.T.."
    ".T....T..."
  , "PLAINS", "" },
/* 032,71 */ {
    "...,=...MM"
    "....=...MM"
    "....=...MM"
    ",...=...MM"
    "....=....M"
    "....=....M"
    "....=....."
    "....=....."
    "....=.,..."
  , "KINGS ROAD", "" },
/* 033,71 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    ".MMM......"
  , "GRAY PEAKS", "" },
/* 034,71 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    ".MMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 035,71 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 036,71 */ {
    "MMMM...MMM"
    "MMM...,.MM"
    "MMM....MMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 037,71 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 038,71 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 039,71 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 040,71 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 041,71 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 042,71 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 043,71 */ {
    "MMMMMMMM.."
    "MMMMMMMM.."
    "MMMMMMMMM,"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 044,71 */ {
    ".........."
    ".........,"
    ".........."
    ".,........"
    "..,......."
    "M........."
    "M....,...."
    "ssssssssss"
    "ssssssssss"
  , "PLAINS", "" },
/* 045,71 */ {
    ".,...,,..."
    "...,.,...."
    ".........."
    ".........."
    "........,."
    ".*........"
    "*........."
    "ssssss...."
    "csssssssss"
  , "PLAINS", "" },
/* 046,71 */ {
    ".........."
    "..,......."
    "....,....."
    ".....,...."
    ".........."
    "..,.....,."
    ".........."
    "...,......"
    "sssss....."
  , "PLAINS", "" },
/* 047,71 */ {
    "..,...,.,."
    ".........."
    ".........."
    ".........."
    ".........."
    ".........."
    ".........."
    "...,......"
    ".....,ssss"
  , "PLAINS", "" },
/* 048,71 */ {
    ".....,...."
    ".......,.."
    "........,."
    ".,........"
    ".....,...."
    ".........."
    "......,..s"
    "....ssssss"
    "ssssssssss"
  , "PLAINS", "" },
/* 049,71 */ {
    "....ssss~~"
    "....ssss~~"
    "....sss~~~"
    "....sss~~~"
    ".,..sss~~~"
    "....sss~~~"
    "sss..ss~~~"
    "sssss.ss~~"
    "ssssssss~~"
  , "PLAINS", "" },
/* 050,71 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 051,71 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 052,71 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 053,71 */ {
    "~~~~~~~~ss"
    "~~~~~~~~ss"
    "~~~~~~~~ss"
    "~~~~~~~~ss"
    "~~~~~~~~ss"
    "~~~~~~~sss"
    "~~~~~~sss."
    "~~~~~~ss.s"
    "~~~~~sssss"
  , "COAST", "" },
/* 054,71 */ {
    "=ss...T..T"
    "=ssT......"
    "=========."
    "=s....T.=."
    "=.TT...T=="
    "=...T.T..."
    "=T.T.T.sss"
    "=sssssssss"
    "=ssscsssss"
  , "KINGS ROAD", "" },
/* 055,71 */ {
    "T........."
    "*.*.*....."
    ".*........"
    ".*...,...."
    "=========="
    "T........,"
    "ssss......"
    "sssssssss,"
    "ssssssssss"
  , "KINGS ROAD", "" },
/* 056,71 */ {
    ".........."
    ",........."
    ".........."
    ".....,...."
    "=========="
    "......,..."
    ",........."
    ".......,.."
    "ss...,...."
  , "KINGS ROAD", "" },
/* 057,71 */ {
    ".......,.."
    ".........."
    "........,."
    ".S......,."
    "=========="
    ".........."
    "......,..."
    ".........."
    "....,.,..."
  , "KINGS ROAD", "TO STARRIDGE 3E" },
/* 058,71 */ {
    "...,......"
    ".........."
    "........,."
    ".........."
    "=========="
    "...,......"
    ",.,......."
    ".,......,."
    ".......,.."
  , "KINGS ROAD", "" },
/* 059,71 */ {
    ".........."
    ".........."
    ".........."
    ",........."
    "=========="
    ".........,"
    ",........."
    ".......,.,"
    ".........."
  , "KINGS ROAD", "" },
/* 060,71 */ {
    "*.Rr=.Rr.*"
    "..HD=.HD.."
    "....=....."
    "...ppppS.."
    "===pppp==="
    "...pppp..."
    "..Rr=.Rr.."
    "..HD=.HD.."
    "*...=....*"
  , "STARRIDGE", "WELCOME TO STARRIDGE" },
/* 061,71 */ {
    ".........."
    ".,........"
    "...,......"
    ".S,......."
    "=========="
    "...,......"
    ".,........"
    ",........."
    "..,......."
  , "KINGS ROAD", "TO STARRIDGE 1W" },
/* 062,71 */ {
    "....,....."
    "....,....."
    "........T."
    ".........T"
    "=========="
    ".......T.."
    ",.,......."
    ".........."
    "....,...T."
  , "KINGS ROAD", "" },
/* 063,71 */ {
    "....TT...T"
    "......T.T."
    "T..T.T.TTT"
    "........T."
    "=========="
    "...TT....."
    "...T...T.."
    "..T..TTTT."
    ".T.T.T.T.."
  , "KINGS ROAD", "" },
/* 064,71 */ {
    "T.T.T.TTTT"
    "..TT..T..T"
    "TT.T.TTT.."
    "TT.T.T...T"
    "=========="
    "T.TT.TTTTT"
    "T.T.TT...T"
    "...TT.TT.T"
    "T..TTT.T.."
  , "OLD FOREST", "" },
/* 065,71 */ {
    ".TTTTTTTTT"
    "TTTTTTT.TT"
    "..TTTTTT.T"
    "TTS..TTTTT"
    "=========="
    ".TTTT.T.TT"
    ".TTTTTTTTT"
    "TT.TTTTTTT"
    "TTTTTTTTTT"
  , "OLD FOREST", "TO GOLDHOLM 2E" },
/* 066,71 */ {
    "TTTT.TT.TT"
    "TTTTTTT.TT"
    "TTTTTTTTT."
    ".TTTT.TTT."
    "=========="
    "TTTTTT.TT."
    "TTTTTTTTTT"
    "TTTTTTTTT."
    "TTTTT.TTTT"
  , "OLD FOREST", "" },
/* 067,71 */ {
    "*.Rr=.Rr.*"
    "..HD=.HD.."
    "....=....."
    "...ppppS.."
    "===pppp==="
    "...pppp..."
    "..Rr=.Rr.."
    "..HD=.HD.."
    "*...=....*"
  , "GOLDHOLM", "WELCOME TO GOLDHOLM" },
/* 068,71 */ {
    ".T.=TTTT.T"
    "T..=T.TT.T"
    "T.T=T..T.T"
    "T===..T.TT"
    "==.T..T.T."
    "TTTTT....T"
    ".TTT..T..T"
    "T...T.TT.T"
    "T.T..TT..."
  , "OLD FOREST", "" },
/* 069,71 */ {
    "...T....T."
    ".T...T.T.."
    "......T..."
    ".TTTT....T"
    "T......T.."
    "T.TT.TTT.."
    ".T....T..."
    ".TTTT...T."
    "TT...T...."
  , "PLAINS", "" },
/* 070,71 */ {
    ".......T.T"
    ".....T.T.."
    "..TT.....T"
    "T.T...T..T"
    ".TTTTTTT.."
    "T.T.TTT..T"
    "..T....T.T"
    ".T...T..TT"
    "....T.TTT."
  , "OLD FOREST", "" },
/* 071,71 */ {
    "..T.T...T."
    "T.TT.....T"
    ".TT.TTTT.."
    ".T.T....T."
    "..TT.TT.TT"
    "....T....T"
    "..T.TTTT.."
    "...TT...T."
    ".T.T.T..TT"
  , "OLD FOREST", "" },
/* 072,71 */ {
    "T.......T."
    "......T..."
    "..TT.T...T"
    "T...T..TTT"
    "T..T.T.T.T"
    ".T...T...."
    ".T..T...T."
    ".......T.."
    "TTTT..T..."
  , "PLAINS", "" },
/* 073,71 */ {
    ".........."
    "..T..T.T.."
    "....T....."
    "T.......TT"
    "..T....T.."
    "T....T...T"
    "..T...TT.."
    "T...T.T..s"
    "T....T.sss"
  , "PLAINS", "" },
/* 074,71 */ {
    "..,......,"
    "........,s"
    "........ss"
    "...T..sscs"
    "..T.sssscs"
    "T.ssssssss"
    "ssssssssss"
    "ssscssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 075,71 */ {
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 076,71 */ {
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 077,71 */ {
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "scssssssss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 078,71 */ {
    "ssssssssss"
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "cssssssssc"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 079,71 */ {
    "ssss..,.=="
    "sssscs..,."
    "sssscsss.,"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 080,71 */ {
    "=.......,."
    "=........."
    "=...,..sss"
    "=cssssssss"
    "===cssssss"
    "ss=sssssss"
    "ss==ssssss"
    "sss=ssssss"
    "sss=ssssss"
  , "DUNE WASTES", "" },
/* 081,71 */ {
    "..,.ssscss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 082,71 */ {
    "sssssss..."
    "sssssssss."
    "sssscsssss"
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 083,71 */ {
    "....=....."
    "....=....."
    "s..==....."
    "ss.=.,...."
    "sss=...,.."
    "ss==s...,."
    "ss=sss...."
    "ss=ssss..."
    "ss=sssss.."
  , "KINGS ROAD", "" },
/* 084,71 */ {
    "*....,...."
    ".......,.."
    ".....,...,"
    ".........."
    ".........."
    ".........."
    ".........."
    ".,........"
    ".........."
  , "PLAINS", "" },
/* 085,71 */ {
    ",........*"
    ".,,......."
    ".,......*."
    ".........."
    ".........."
    "....*....."
    "....*.*.**"
    ".....*..*."
    "*....*.***"
  , "MEADOWS", "" },
/* 086,71 */ {
    "..*...*..."
    ".....*..*."
    ".*......*."
    "*..*.***.."
    ".**....**."
    "**.*......"
    ".*.**....*"
    ".*.*.*...."
    "..*....*.*"
  , "MEADOWS", "" },
/* 087,71 */ {
    ",...,,...."
    "..,.,....."
    ".........."
    ".........."
    ".......,.."
    ".........."
    ".........."
    ".........."
    "*........."
  , "PLAINS", "" },
/* 088,71 */ {
    ".........."
    ".,........"
    "...,..*.**"
    "....P*...."
    "...**.*..."
    ".**.*.*P.."
    ".*..*.*.*."
    "..P..*...."
    "..P......."
  , "MEADOWS", "" },
/* 089,71 */ {
    ".,...*.*.."
    ".*....*.*."
    "*......**."
    "**....*..*"
    "...*......"
    "..*......."
    "......*..."
    "..P*...*.."
    "....P.*..."
  , "MEADOWS", "" },
/* 090,71 */ {
    "....*..*.."
    "......*..*"
    "*......**."
    "*.....**.*"
    "*.*.**.*.*"
    ".*..*..*.*"
    ".*.**P..*."
    ".....P...."
    "**..*..P.P"
  , "MEADOWS", "" },
/* 091,71 */ {
    ".........."
    ".........."
    "...**....."
    ".........."
    "*....*...."
    ".*........"
    "...*.*...."
    ".......,.."
    "......,..."
  , "PLAINS", "" },
/* 092,71 */ {
    ".........,"
    ".........."
    "...,......"
    ".......T.."
    ".........."
    "........T."
    "........T."
    ".........."
    ".........."
  , "PLAINS", "" },
/* 093,71 */ {
    ".........."
    ",........."
    ".........."
    "...T......"
    ".........."
    "........T."
    ".........."
    "T.T.T..T.T"
    "...T......"
  , "PLAINS", "" },
/* 094,71 */ {
    ".........."
    "......,..."
    ".........."
    ".........."
    ".........."
    ".........."
    "T.T.....ss"
    "......ssss"
    "..T.ssssss"
  , "PLAINS", "" },
/* 095,71 */ {
    "...,......"
    ".........s"
    ",.....ssss"
    "....ssssss"
    ".Tssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 096,71 */ {
    ".sssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssscssssss"
  , "DUNE WASTES", "" },
/* 097,71 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 098,71 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 099,71 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssscssssss"
  , "DUNE WASTES", "" },
/* 100,71 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 101,71 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 102,71 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 103,71 */ {
    ".........."
    "c........."
    "ss,......."
    "ssss......"
    "sssss....."
    "sscssss..."
    "sssssssss,"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 104,71 */ {
    "*.Rr=.Rr.*"
    "..HD=.HD.."
    "....=....."
    "...ppppS.."
    "===pppp==="
    "...pppp..."
    "..Rr=.Rr.."
    "..HD=.HD.."
    "*...=....*"
  , "THORNHILL", "WELCOME TO THORNHILL" },
/* 105,71 */ {
    "...,.....M"
    ".....,...M"
    "....,....M"
    ".........M"
    "=....,...."
    "=..,......"
    "=.,......."
    "=...,....."
    "=.,...,..."
  , "KINGS ROAD", "" },
/* 106,71 */ {
    "MMMMMMMMMM"
    "MMMMMMMM.M"
    "MMMMMMMM.."
    "MMMMMMM.,."
    ".MMMM....,"
    "..,.,....."
    ".........."
    "......,..."
    ".........."
  , "GRAY PEAKS", "" },
/* 107,71 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    ".MMMMMMMMM"
    ",MMMMMMMMM"
    "..MMMMMMMM"
  , "GRAY PEAKS", "" },
/* 108,71 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 109,71 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 110,71 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 111,71 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 112,71 */ {
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 113,71 */ {
    "MMMMM..,.,"
    "MMMMM...,."
    "MMMMM....."
    "MMMMM....."
    "MMMMMM...,"
    "MMMMMM...."
    "MMMMMMMM.."
    "MMMMMMMMM."
    "MMMMMMMMMM"
  , "GRAY PEAKS", "" },
/* 114,71 */ {
    "......scss"
    ".....sssss"
    "....ssssss"
    "....ssssss"
    "...scsssss"
    "..sscsssss"
    "..ssssssss"
    ".sssssssss"
    ".sssssssss"
  , "DUNE WASTES", "" },
/* 115,71 */ {
    "ssssssssss"
    "sssscsssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "ssscssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 116,71 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sscsssscss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 117,71 */ {
    "ss.....,.,"
    "sss.*.*..."
    "sssss....."
    "sssssss..*"
    "ssssssssss"
    "sssscsssss"
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 118,71 */ {
    ".........."
    ".........."
    "**.*.,...."
    "....*....."
    ".**...*..*"
    "ssss......"
    "ssssscs.*."
    "ssssssssss"
    "ssssssssss"
  , "PLAINS", "" },
/* 119,71 */ {
    ",...*..*.*"
    "..****...."
    ",.*.*..*.."
    "*....*...."
    "...*...*.."
    "..*..*...P"
    ".....*...."
    "*.***....."
    "sss.**...."
  , "MEADOWS", "" },
/* 120,71 */ {
    "....ss~~~~"
    "...*ss~~~~"
    "..*.ss~~~~"
    "*.*.ss~~~~"
    ".**.ss~~~~"
    ".*..ss~~~~"
    "*.**.s~~~~"
    ".**.*ss~~~"
    "*..**ss~~~"
  , "COAST", "" },
/* 121,71 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 122,71 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 123,71 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 124,71 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 125,71 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 126,71 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 127,71 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
};
