#pragma bank 255
#include <gb/gb.h>
#include "world/world.h"
/* Only gb.h (BANKREF), not engine.h: through gbdk/emu_debug.h it adds 2 bytes of bank 0 and of RAM to every file
   that includes it, and 96 of these files overflowed bank 0.
   PLAY GAME 2 world row 84: screens x = 0..127 at y = 84, 128 bytes each = one full 16 KB ROM bank.
   Per screen: 9 rows of 10 metatile chars (legend: ow_metatiles in assets/tilesets/ts_overworld.c),
   the HUD name and the text of its sign ("" = no sign). Format: assets/world/world.h */
BANKREF(world_r84)
const wscreen_t world_r84[WORLD_W] = {
/* 000,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 001,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 002,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 003,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 004,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 005,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 006,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 007,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 008,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 009,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 010,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 011,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 012,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 013,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 014,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 015,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 016,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 017,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 018,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 019,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 020,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 021,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 022,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 023,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 024,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 025,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 026,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 027,84 */ {
    "~~~~ssssss"
    "~~~~~sssss"
    "~~~~~~ssss"
    "~~~~~~~sss"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "COAST", "" },
/* 028,84 */ {
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "~~~sssssss"
    "~~~~~sssss"
    "~~~~~~~sss"
    "~~~~~~~~ss"
    "~~~~~~~~~~"
  , "COAST", "" },
/* 029,84 */ {
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 030,84 */ {
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 031,84 */ {
    "*.Rr=.Rr.*"
    "..HD=.HD.."
    "....=....."
    "...ppppS.."
    "===pppp==="
    "...pppp..."
    "..Rr=.Rr.."
    "..HD=.HD.."
    "*...=....*"
  , "REDCROSS", "WELCOME TO REDCROSS" },
/* 032,84 */ {
    "ssss=sssss"
    "ssss=sssss"
    "ss===sssss"
    "ss=s=sssss"
    "=========="
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 033,84 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "=========="
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssscss"
  , "DUNE WASTES", "" },
/* 034,84 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "=========="
    "sscsssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 035,84 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "=========="
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 036,84 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "=========="
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "ssssssscss"
  , "DUNE WASTES", "" },
/* 037,84 */ {
    "*.Rr=.Rr.*"
    "..HD=.HD.."
    "....=....."
    "...ppppS.."
    "===pppp==="
    "...pppp..."
    "..Rr=.Rr.."
    "..HD=.HD.."
    "*...=....*"
  , "HOLLYFIELD", "WELCOME TO HOLLYFIELD" },
/* 038,84 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssssscs"
    "=========="
    "ssssssssss"
    "ssscssssss"
    "ssssssss~~"
    "ssssss~~~~"
  , "DUNE WASTES", "" },
/* 039,84 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "=========="
    "ssssssssss"
    "ssssssssss"
    "~~~sssssss"
    "~~~~~~~~~~"
  , "DUNE WASTES", "" },
/* 040,84 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "=========="
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 041,84 */ {
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "ssssssssss"
    "=========="
    "ssssssssss"
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 042,84 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "=========="
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 043,84 */ {
    "ssssssssss"
    "sssscsssss"
    "ssssssssss"
    "ssssssssss"
    "=========="
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 044,84 */ {
    "*.Rr=.Rr.*"
    "..HD=.HD.."
    "....=....."
    "...ppppS.."
    "===pppp==="
    "...pppp..."
    "..Rr=.Rr.."
    "..HD=.HD.."
    "*...=....*"
  , "REDMOUTH", "WELCOME TO REDMOUTH" },
/* 045,84 */ {
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssss~~~~~"
  , "DUNE WASTES", "" },
/* 046,84 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "DUNE WASTES", "" },
/* 047,84 */ {
    "ssssssssss"
    "ssssssssss"
    "sssssssss~"
    "ssssssss~~"
    "ssssss~~~~"
    "sss~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "COAST", "" },
/* 048,84 */ {
    "ss~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 049,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 050,84 */ {
    "ssssssssss"
    "~~ssssssss"
    "~~~~~sssss"
    "~~~~~~~sss"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "COAST", "" },
/* 051,84 */ {
    "sssssss~~~"
    "ssssss~~~~"
    "ssss~~~~~~"
    "sss~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "COAST", "" },
/* 052,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 053,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 054,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 055,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 056,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 057,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 058,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 059,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 060,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 061,84 */ {
    "~~~~ssssss"
    "~~~~~sssss"
    "~~~~~sssss"
    "~~~~~~ssss"
    "~~~~~~~sss"
    "~~~~~~~~ss"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "COAST", "" },
/* 062,84 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssss~~~~~s"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "COAST", "" },
/* 063,84 */ {
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "~sssssssss"
    "~~~sssssss"
  , "DUNE WASTES", "" },
/* 064,84 */ {
    "csssssssss"
    "csssssssss"
    "ssssssscss"
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
    "ssssssss~~"
    "ssssss~~~~"
    "ssss~~~~~~"
  , "DUNE WASTES", "" },
/* 065,84 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sss~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "COAST", "" },
/* 066,84 */ {
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
    "ssss~sssss"
    "~~~~~~~~~s"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "COAST", "" },
/* 067,84 */ {
    "ssssssssss"
    "csssssssss"
    "ssssssssss"
    "ssssssssss"
    "ss~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "COAST", "" },
/* 068,84 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "COAST", "" },
/* 069,84 */ {
    "ssscssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "~~~~ssssss"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "COAST", "" },
/* 070,84 */ {
    "ssssssssss"
    "sssscsssss"
    "ssssssssss"
    "ssssssssss"
    "s~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "COAST", "" },
/* 071,84 */ {
    "ssssssss~~"
    "ssssss~~~~"
    "ssss~~~~~~"
    "sss~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "COAST", "" },
/* 072,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 073,84 */ {
    "~sssssssss"
    "~~~sssssss"
    "~~~~ssssss"
    "~~~~~sssss"
    "~~~~~~ssss"
    "~~~~~~~~ss"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "COAST", "" },
/* 074,84 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "~~~sssssss"
    "~~~~~sssss"
    "~~~~~~~sss"
  , "DUNE WASTES", "" },
/* 075,84 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
  , "DUNE WASTES", "" },
/* 076,84 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 077,84 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssssssc"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 078,84 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
  , "DUNE WASTES", "" },
/* 079,84 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 080,84 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "sssssssssc"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 081,84 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
  , "DUNE WASTES", "" },
/* 082,84 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssss======"
    "sss==sssss"
    "sss=ssssss"
  , "DUNE WASTES", "" },
/* 083,84 */ {
    "ss==ssssss"
    "ss=sssssss"
    "cs=sssssss"
    "ss=sssssss"
    "ss=sssssss"
    "===sssssss"
    "=scsssssss"
    "sssssssssc"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 084,84 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 085,84 */ {
    "ssssssssss"
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 086,84 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sscsssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 087,84 */ {
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "csssscssss"
  , "DUNE WASTES", "" },
/* 088,84 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 089,84 */ {
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssscssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 090,84 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssss~~~~~"
    "ss~~~~~~~~"
    "~~~~~~~~~~"
  , "DUNE WASTES", "" },
/* 091,84 */ {
    "ssssssssss"
    "ssssssscss"
    "ssssssssss"
    "sssssss~~~"
    "ssss~~~~~~"
    "s~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "COAST", "" },
/* 092,84 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "COAST", "" },
/* 093,84 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "~~~~~~~~~s"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "COAST", "" },
/* 094,84 */ {
    "ssssssssss"
    "ssssssssss"
    "ssss~~~~~~"
    "ss~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "COAST", "" },
/* 095,84 */ {
    "ssssssssss"
    "sss~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "COAST", "" },
/* 096,84 */ {
    "ssssssssss"
    "ssssssssss"
    "~~~~~sssss"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "COAST", "" },
/* 097,84 */ {
    "csssssssss"
    "ssssssscss"
    "ssssssssss"
    "~~~~~~~~ss"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "COAST", "" },
/* 098,84 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssscssss"
    "ssssssssss"
    "~sssssssss"
    "~~~sssssss"
    "~~~~~sssss"
    "~~~~~~~sss"
  , "DUNE WASTES", "" },
/* 099,84 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "csssssssss"
    "ssssssscss"
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 100,84 */ {
    "csssssssss"
    "ssssssssss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 101,84 */ {
    "ssssssssss"
    "ssssssssss"
    "ssscssssss"
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 102,84 */ {
    "*.Rr=.Rr.*"
    "..HD=.HD.."
    "....=....."
    "...ppppS.."
    "===pppp==="
    "...pppp..."
    "..Rr=.Rr.."
    "..HD=.HD.."
    "*...=....*"
  , "WESTMOUTH", "WELCOME TO WESTMOUTH" },
/* 103,84 */ {
    "ssssssssss"
    "scsssscsss"
    "sssssscsss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 104,84 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssscssssss"
    "ssssscssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 105,84 */ {
    "sssscssssc"
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
    "sssscsssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 106,84 */ {
    "ssssssssss"
    "ssssssssss"
    "sssssscsss"
    "sssssssscs"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 107,84 */ {
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssscss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 108,84 */ {
    "sscsssssss"
    "sssssssssc"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 109,84 */ {
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 110,84 */ {
    "ssssssssss"
    "ssssssssss"
    "csssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 111,84 */ {
    "sscsssssss"
    "sssscsssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "scssssssss"
  , "DUNE WASTES", "" },
/* 112,84 */ {
    "ssssssssss"
    "ssscssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
    "ssssssssss"
  , "DUNE WASTES", "" },
/* 113,84 */ {
    "*.Rr=.Rr.*"
    "..HD=.HD.."
    "....=....."
    "...ppppS.."
    "===pppp==="
    "...pppp..."
    "..Rr=.Rr.."
    "..HD=.HD.."
    "*...=....*"
  , "SALTWICK", "WELCOME TO SALTWICK" },
/* 114,84 */ {
    "sssssssss~"
    "sssssss~~~"
    "sssss~~~~~"
    "ssss~~~~~~"
    "ss~~~~~~~~"
    "s~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "COAST", "" },
/* 115,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 116,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 117,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "SEA", "" },
/* 118,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 119,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 120,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 121,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 122,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 123,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 124,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 125,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 126,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
/* 127,84 */ {
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
    "~~~~~~~~~~"
  , "OPEN SEA", "" },
};
