const C={b:['b','c','.','.'], a:['a','b','c','b','c','.','.','.','.'],
         d:['b','c','d','b','c','.','.','.','.'], r:['a','b','c','d','b','c','.','.','.','.'],
         A:['a','b','c','b','c','c','.','.','.'], R:['a','b','c','d','b','c','c','.','.','.']};
const base={maxStraight:4,minOpen:34,minDist:9,jitter:2,cap:25000,ms:70000,iters:6000,
            routes:3,freeMin:75,haulMax:10,minHaul:4};
const F=(o)=>Object.assign({},base,o);
module.exports=[
/*1*/  F({pool:C.a,minLen:4,maxLen:7,noDeath:1,routes:4,good:170}),
/*2*/  F({pool:C.a,minLen:5,maxLen:8,noDeath:1,routes:4,good:170}),
/*3*/  F({pool:C.d,minLen:5,maxLen:8,noDeath:1,routes:4,good:170}),
/*4*/  F({pool:C.a,minLen:5,maxLen:9,noDeath:1,pieces:[{ch:'o',at:'cut',push:true}],
          must:[{cell:'o',repl:'#'}],good:380}),
/*5*/  F({pool:C.a,minLen:6,maxLen:10,noDeath:1,pieces:[{ch:'o',at:'cut',push:true},{ch:'o',at:'any'}],
          must:[{cell:'o',repl:'#'}],good:380}),
/*6*/  F({pool:C.a,minLen:5,maxLen:9,wantDeath:1,pieces:[{ch:'2',at:'any',notCut:true}],good:170}),
/*7*/  F({pool:C.a,minLen:5,maxLen:9,wantDeath:1,freeMin:70,
          pieces:[{ch:'2',at:'any',notCut:true},{ch:'2',at:'any',notCut:true}],good:170}),
/*8*/  F({pool:C.a,minLen:6,maxLen:10,noDeath:1,minHaul:4,
          pieces:[{ch:'-',at:'cut'},{ch:'=',at:'any',notCut:true},{ch:'y',at:'any'},{ch:'y',at:'any'}],
          must:[{cell:'y',repl:'.'}],good:380}),
/*9*/  F({pool:C.A,minDist:7,minLen:6,maxLen:11,noDeath:1,minHaul:4,freeMin:65,
          pieces:[{ch:'o',at:'cut'},{ch:'x',at:'any'},{ch:'x',at:'any'}],
          must:[{cell:'x',repl:'.'}],good:380}),
/*10*/ F({pool:C.A,minDist:7,minLen:6,maxLen:11,wantDeath:1,minHaul:4,freeMin:65,
          pieces:[{ch:'2',at:'cut'},{ch:'x',at:'any'},{ch:'x',at:'any'}],
          must:[{cell:'x',repl:'.'}],good:380}),
/*11*/ F({pool:C.R,minDist:7,minLen:6,maxLen:12,noDeath:1,minHaul:4,freeMin:65,haulMax:14,
          pieces:[{ch:'-',at:'cut'},{ch:'x',at:'any'},{ch:'x',at:'any'},{ch:'y',at:'any'},{ch:'y',at:'any'}],
          must:[{cell:'y',repl:'.'}],good:380}),
/*12*/ F({pool:C.R,minDist:7,minLen:6,maxLen:12,wantDeath:1,minHaul:4,freeMin:60,
          pieces:[{ch:'-',at:'cut'},{ch:'2',at:'any',notCut:true},{ch:'y',at:'any'},{ch:'y',at:'any'}],
          must:[{cell:'y',repl:'.'}],good:380}),
/*13*/ F({pool:C.A,minDist:7,minLen:5,maxLen:10,wantDeath:1,freeMin:65,
          pieces:[{ch:'o',at:'any'},{ch:'2',at:'any',notCut:true}],good:170}),
/*14*/ F({pool:C.A,minDist:7,minLen:6,maxLen:12,wantDeath:1,minHaul:4,freeMin:60,
          pieces:[{ch:'o',at:'any'},{ch:'-',at:'cut'},{ch:'=',at:'any',notCut:true},
                  {ch:'2',at:'any',notCut:true},{ch:'y',at:'any'},{ch:'y',at:'any'}],
          must:[{cell:'y',repl:'.'}],good:380}),
/*15*/ F({pool:C.R,minDist:6,minLen:6,maxLen:12,ms:150000,wantDeath:1,minHaul:4,freeMin:55,
          pieces:[{ch:'2',at:'cut'},{ch:'-',at:'any',notCut:true},{ch:'=',at:'any',notCut:true},{ch:'x',at:'any'},{ch:'x',at:'any'},{ch:'y',at:'any'},{ch:'y',at:'any'}],
          must:[{cell:'x',repl:'.'},{cell:'y',repl:'.'}],good:600}),
/*16*/ F({pool:C.R,minDist:6,minLen:6,maxLen:13,wantDeath:1,minHaul:1,freeMin:55,ms:150000,
          pieces:[{ch:'o',at:'cut',push:true},{ch:'2',at:'cut'},{ch:'-',at:'any',notCut:true},{ch:'=',at:'any',notCut:true},
                  {ch:'x',at:'any'},{ch:'x',at:'any'},{ch:'y',at:'any'},{ch:'y',at:'any'},{ch:'2',at:'any',notCut:true}],
          must:[{cell:'x',repl:'.'},{cell:'y',repl:'.'},{cell:'o',repl:'#'}],good:850}),
];
