// wall skeletons for the 16 floors. '?' = card slot filled by the search.
// fixed pieces: o crate, 2 guard, - closed door, = open door, x bomb, y switch, ^ stair, p start
const P={
  cards:['b','c','b','c','a','.'],
  rich :['b','c','d','b','c','a','.'],
  lean :['b','c','a','.','.'],
};
module.exports=[
{ // 1 - open room: a press spends a card, a card on the floor is picked up
 tpl:["##########",
      "#p?.?.?.?#",
      "#.?.?.?.?#",
      "#?.?##?.?#",
      "#.?.##.?.#",
      "#?.?.?.?^#",
      "#.?.?.?.?#",
      "#?.?.?.?.#",
      "##########"],
 pool:P.cards, cfg:{iters:300,minLen:5,maxLen:8,noDeath:1,routes:4,minHaul:3,freeMin:70}},

{ // 2 - LIFO: the last card you pick up is the next one you spend
 tpl:["##########",
      "#p?.?.?.?#",
      "#.?.###?.#",
      "#?.?.?.?.#",
      "#.###.###.#".slice(0,10),
      "#?.?.?.?.#",
      "#.?.###?.#",
      "#?.?.?.^.#",
      "##########"],
 pool:P.cards, cfg:{iters:300,minLen:5,maxLen:9,noDeath:1,routes:4,minHaul:3,freeMin:65}},

{ // 3 - runs stop at walls: pick the rung
 tpl:["##########",
      "#p?.?.?.?#",
      "#.#?.?#?.#",
      "#?#.?.#?.#",
      "#.?.?.?.?#",
      "#?#.?.#?.#",
      "#.#?.?#?.#",
      "#?.?.?.^.#",
      "##########"],
 pool:P.rich, cfg:{iters:300,minLen:5,maxLen:9,noDeath:1,routes:4,minHaul:3,freeMin:65}},

{ // 4 - crate: the junction is blocked, push it out of the way
 tpl:["##########",
      "#p?.?.?.?#",
      "#.?.?.?.?#",
      "#?.?.?.?.#",
      "#.###.##.#",
      "#?.?.o.?.#",
      "#####.####",
      "#?.?.?.^.#",
      "##########"],
 pool:P.cards, cfg:{iters:300,minLen:5,maxLen:10,noDeath:1,routes:4,minHaul:3,freeMin:60},
 must:{cell:'o',repl:'#'}},

{ // 5 - two crates: one opens the way, one opens a card lane
 tpl:["##########",
      "#p?.?.?.?#",
      "#.?.?.?.?#",
      "#?.?.?.?.#",
      "#.###.##.#",
      "#?.o.o.?.#",
      "#####.####",
      "#?.?.?.^.#",
      "##########"],
 pool:P.cards, cfg:{iters:300,minLen:6,maxLen:11,noDeath:1,routes:4,minHaul:3,freeMin:60},
 must:{cell:'o',repl:'#'}},

{ // 6 - guard: he punishes stopping, not passing
 tpl:["##########",
      "#p?.?.?.?#",
      "#.?.?.?.?#",
      "#?.?.?.?.#",
      "#.###.##.#",
      "#?.?.2.?.#",
      "#####.####",
      "#?.?.?.^.#",
      "##########"],
 pool:P.cards, cfg:{iters:300,minLen:5,maxLen:10,wantDeath:1,routes:4,minHaul:3,freeMin:55}},

{ // 7 - two guards: exact card length as survival
 tpl:["##########",
      "#p?.?.?.?#",
      "#.?.?.?.?#",
      "#?.#2#?.?#",
      "#.?.?.?.?#",
      "#?.#2#?.?#",
      "#.?.?.?.?#",
      "#?.?.?.^.#",
      "##########"],
 pool:P.cards, cfg:{iters:300,minLen:5,maxLen:10,wantDeath:1,routes:4,minHaul:3,freeMin:55}},

{ // 8 - switch and doors: the flip goes both ways
 tpl:["##########",
      "#p?.?.?.?#",
      "#.?.?.?.?#",
      "#?.?.?.?.#",
      "#.##=.##-#",
      "#?.?.?.?^#",
      "#.?.y.?.?#",
      "#?.?.?.?.#",
      "##########"],
 pool:P.cards, cfg:{iters:300,minLen:6,maxLen:11,noDeath:1,routes:4,minHaul:2,freeMin:55},
 must:{cell:'y',repl:'.'}},

{ // 9 - bomb: reach what cannot be pushed
 tpl:["##########",
      "#p?.?.?.?#",
      "#.?.?.?.?#",
      "#?.?.x.?.#",
      "#.###.##.#",
      "#?.?.o.?.#",
      "#####.####",
      "#?.?.?.^.#",
      "##########"],
 pool:P.cards, cfg:{iters:300,minLen:6,maxLen:12,noDeath:1,routes:3,minHaul:2,freeMin:50},
 must:{cell:'x',repl:'.'}},

{ // 10 - bomb against guard: throw range is kill range
 tpl:["##########",
      "#p?.?.?.?#",
      "#.?.?.?.?#",
      "#?.?.x.?.#",
      "#.###.##.#",
      "#?.?.2.?.#",
      "#####.####",
      "#?.?.?.^.#",
      "##########"],
 pool:P.cards, cfg:{iters:300,minLen:6,maxLen:12,wantDeath:1,routes:3,minHaul:2,freeMin:50},
 must:{cell:'x',repl:'.'}},

{ // 11 - the fork: pick what the rest of the run gets to use
 tpl:["##########",
      "#p?.?.?.?#",
      "#.?.x.y.?#",
      "#?.?.?.?.#",
      "#.?.y.x.?#",
      "#?.?.?.?.#",
      "#.####-###",
      "#?.?.?.^.#",
      "##########"],
 pool:P.rich, cfg:{iters:300,minLen:6,maxLen:12,noDeath:1,routes:4,minHaul:2,freeMin:55}},

{ // 12 - two sealed shafts, open the one you brought the key for
 tpl:["##########",
      "#p?.?.?.?#",
      "#.##-##.##".slice(0,10),
      "#?.?#?.?.#",
      "#.###2##.#",
      "#?.?#?.?.#",
      "#.####.###",
      "#?.?.?.^.#",
      "##########"],
 pool:P.rich, cfg:{iters:300,minLen:5,maxLen:12,wantDeath:1,routes:3,minHaul:2,freeMin:50}},

{ // 13 - the crate is a brake, the guard is what happens without one
 tpl:["##########",
      "#p?.?.?.?#",
      "#.?.?.?.?#",
      "#?.?.o.?2#",
      "#.###.##.#",
      "#?.?.?.?.#",
      "#####.####",
      "#?.?.?.^.#",
      "##########"],
 pool:P.cards, cfg:{iters:300,minLen:5,maxLen:11,wantDeath:1,routes:4,minHaul:3,freeMin:50}},

{ // 14 - door, crate and guard, order fixed by the geometry
 tpl:["##########",
      "#p?.?.?.?#",
      "#.?.?.y.?#",
      "#?.o.?.?.#",
      "#.###=##.#",
      "#?.?.?.2.#",
      "#####-####",
      "#?.?.?.^.#",
      "##########"],
 pool:P.cards, cfg:{iters:300,minLen:6,maxLen:13,wantDeath:1,routes:3,minHaul:2,freeMin:45}},

{ // 15 - bomb the guard, then find the switch, on that budget
 tpl:["##########",
      "#p?.?.x.?#",
      "#.?.?.?.?#",
      "#?.#2#?.y#",
      "#.?.?.?.?#",
      "#?.?.?.?.#",
      "#.####-###",
      "#?.?.?.^.#",
      "##########"],
 pool:P.rich, cfg:{iters:300,minLen:7,maxLen:14,wantDeath:1,routes:3,minHaul:2,freeMin:45}},

{ // 16 - crate lets you in, bomb lets you past, switch lets you out
 tpl:["##########",
      "#p?.?.?.?#",
      "#.###.##.#",
      "#?.o.?.?.#",
      "#.##2#?.y#",
      "#?.?.x.?.#",
      "#.####-###",
      "#?.?.?.^.#",
      "##########"],
 pool:P.rich, cfg:{iters:300,minLen:7,maxLen:14,wantDeath:1,routes:3,minHaul:2,freeMin:40}},
];
