// rotamaze - cover art. writes labelgen.p8 (a throwaway cart that draws the
// 128x128 label with real pico-8 calls), runs it headlessly, and splices the
// dump into game.p8 with the shared label-tool.js.
//   node label.js
'use strict';
const fs = require('fs');
const path = require('path');
const cp = require('child_process');
const L = require('./lib.js');

const DIR = path.join(__dirname, '..');
const ROOT = path.join(DIR, '..', '..');
const PICO = 'C:/Program Files (x86)/PICO-8/pico8.exe';

// pick a 6x4 crop out of the shipped pool that reads well when blown up:
// a decent number of walls, nothing sealed, and at least one thick wall.
function pickCrop(mazes) {
  let best = null;
  mazes.forEach((m, mi) => {
    for (let r = 0; r + 4 <= L.H; r++) for (let c = 0; c + 6 <= L.W; c++) {
      const tiles = [];
      for (let y = 0; y < 4; y++) for (let x = 0; x < 6; x++) tiles.push(m.board[(r + y) * L.W + c + x]);
      if (tiles.some(w => w === 15)) continue;
      const walls = tiles.reduce((s, w) => s + (w & 1) + ((w >> 1) & 1) + ((w >> 2) & 1) + ((w >> 3) & 1), 0);
      const empty = tiles.filter(w => w === 0).length;
      let thick = 0;
      for (let y = 0; y < 4; y++) for (let x = 0; x < 5; x++) {
        if ((tiles[y * 6 + x] & 2) && (tiles[y * 6 + x + 1] & 8)) thick++;
      }
      // want busy but not solid, a couple of empty tiles for the props
      const score = Math.abs(walls - 30) + Math.abs(empty - 2) * 2 + (thick ? 0 : 4);
      if (!best || score < best.score) best = { score, tiles, mi, c, r, walls, empty, thick };
    }
  });
  return best;
}

function labelgen(crop) {
  const rows = [];
  for (let y = 0; y < 4; y++) {
    rows.push('"' + crop.tiles.slice(y * 6, y * 6 + 6).map(w => w.toString(16)).join('') + '"');
  }
  return `pico-8 cartridge // http://www.pico-8.com
version 43
__lua__
-- rotamaze label generator
-- generated by tools/label.js - do not hand edit
hx="0123456789abcdef"

-- the player token, same shape as the in-game sprite
pl={"........",
    "...##...",
    "..####..",
    ".##..##.",
    ".######.",
    ".######.",
    "..####..",
    "........"}

function blob(px,py,g,s,col)
 for y=0,7 do
  for x=0,7 do
   if sub(g[y+1],x+1,x+1)=="#" then
    rectfill(px+x*s,py+y*s,px+x*s+s-1,py+y*s+s-1,col)
   end
  end
 end
end

-- a 2px wall on one side of a 16px tile
function wall(x,y,d)
 if d==0 then rectfill(x,y,x+15,y+1,7) end
 if d==1 then rectfill(x+14,y,x+15,y+15,7) end
 if d==2 then rectfill(x,y+14,x+15,y+15,7) end
 if d==3 then rectfill(x,y,x+1,y+15,7) end
end

-- clockwise arrow, the one motif the whole game turns on.
-- a runs backwards because pico-8's sin is screen-flipped: falling a
-- sweeps clockwise, from upper left over the top and down the right.
function arrow(cx,cy,r,col,t,hs)
 for a=0.44,0.0,-0.002 do
  circfill(cx+cos(a)*r,cy+sin(a)*r,t,col)
 end
 for i=0,hs do
  line(cx+r-hs+i,cy+i,cx+r+hs-i,cy+i,col)
 end
end

cls(0)

-- stone bands top and bottom
fillp(0x5a5a)
rectfill(0,0,127,6,7)
rectfill(0,121,127,127,7)
fillp()

-- title plaque
rect(6,10,121,46,7)
rect(8,12,119,44,7)
print("\\^w\\^trotamaze",32,20,7)
print("a maze that turns",30,36,7)

-- the board, four rows of six tiles at 16px
lay={${rows.join(',')}}
for r=0,3 do
 for c=0,5 do
  local w=tonum("0x"..sub(lay[r+1],c+1,c+1))
  local x,y=16+c*16,54+r*16
  if w&1>0 then wall(x,y,0) end
  if w&2>0 then wall(x,y,1) end
  if w&4>0 then wall(x,y,2) end
  if w&8>0 then wall(x,y,3) end
 end
end

-- the exit shimmers at the far end
fillp(0x5a5a)
rectfill(98,56,109,67,7)
fillp()

-- the player and the arrow get a black outline so they stay separate
-- from the wall lines behind them
for ox=-2,2 do
 for oy=-2,2 do
  blob(16+ox,102+oy,pl,2,0)
 end
end
blob(16,102,pl,2,7)
arrow(56,94,11,0,3,7)
arrow(56,94,11,7,1,5)

printh("@@begin")
for y=0,127 do
 local s=""
 for x=0,127 do
  s=s..sub(hx,pget(x,y)+1,pget(x,y)+1)
 end
 printh(s)
end
printh("@@end")
extcmd("shutdown")
__gfx__
`;
}

function main() {
  const mazes = JSON.parse(fs.readFileSync(path.join(__dirname, 'mazes.json'), 'utf8'));
  const crop = pickCrop(mazes);
  console.log('crop from maze', crop.mi, 'at', crop.c + ',' + crop.r,
    '- walls', crop.walls, 'empty', crop.empty, 'thick', crop.thick);
  const gen = path.join(DIR, 'labelgen.p8');
  fs.writeFileSync(gen, labelgen(crop));

  const r = cp.spawnSync(PICO, ['-x', gen], { encoding: 'utf8', timeout: 120000 });
  const dump = path.join(DIR, 'labeldump.txt');
  fs.writeFileSync(dump, (r.stdout || '') + (r.stderr || ''));
  if (!/@@begin/.test(fs.readFileSync(dump, 'utf8'))) {
    console.error('labelgen produced no dump');
    process.exit(1);
  }
  const t = cp.spawnSync('node', [path.join(ROOT, 'label-tool.js'), dump,
    path.join(DIR, 'game.p8'), path.join(DIR, 'label.png'), '3'],
    { encoding: 'utf8' });
  console.log((t.stdout || '').trim());
  if (t.stderr) console.error(t.stderr.trim());
  if (t.status !== 0) process.exit(1);
  fs.unlinkSync(dump);
}
main();
