// rotamaze - screenshot harness. builds a copy of the cart with a driver
// that feeds a scripted input string, then dumps whole frames to a text
// file which we turn into png.
//   node shot.js "<input script>" <frame[:name]>...
// input script: one char per frame -  l r u d = arrows, o x = buttons,
// - = nothing.  frames are 1-based.
'use strict';
const fs = require('fs');
const path = require('path');
const cp = require('child_process');
const { writePng } = require('./png.js');

const DIR = path.join(__dirname, '..');
const PICO = 'C:/Program Files (x86)/PICO-8/pico8.exe';
const DUMP = path.join(DIR, "shot.p8l");

function driver(script, frames, maze, exec) {
  let force = maze === null ? '' : ' if tf==1 then loadmz(' + maze + ') end';
  if (exec) force += '\n if tf==1 then ' + exec + ' end';
  const shots = frames.map(f => ' sh[' + f.frame + ']="' + f.name + '"').join('\n');
  return `
-- test driver (generated by tools/shot.js)
_ru=_update _rd=_draw
sb=0 spb=0
function btn(b,pl)
 if b==nil then return sb end
 return (sb\\(2^b))%2>=1
end
function btnp(b,pl)
 if b==nil then return sb end
 return ((sb\\(2^b))%2>=1) and ((spb\\(2^b))%2<1)
end
sh={}
${shots}
inp="${script}"
tf=0
first=true
function _draw() end
function dump(nm)
 for y=0,127 do
  local s=""
  for x=0,127 do
   local c=pget(x,y)
   s=s..sub("0123456789abcdef",c+1,c+1)
  end
  printh(nm.." "..s,"shot",first)
  first=false
 end
end
function _update()
 tf+=1
${force}
 local c=sub(inp,tf,tf)
 sb=0
 if c=="l" then sb=1
 elseif c=="r" then sb=2
 elseif c=="u" then sb=4
 elseif c=="d" then sb=8
 elseif c=="o" then sb=16
 elseif c=="x" then sb=32 end
 _ru()
 spb=sb
 if sh[tf] then _rd() dump(sh[tf]) end
 if tf>=#inp then extcmd("shutdown") end
end
`;
}

function main() {
  const args = process.argv.slice(3);
  let maze = null, crop = null, exec = null;
  const rest = [];
  for (const a of args) {
    if (a.startsWith('maze=')) maze = parseInt(a.slice(5), 10);
    else if (a.startsWith('crop=')) crop = a.slice(5).split(',').map(Number);
    else if (a.startsWith('exec=')) exec = a.slice(5);
    else rest.push(a);
  }
  const script = process.argv[2] || '';
  const frames = rest.map(a => {
    const [f, n] = a.split(':');
    return { frame: parseInt(f, 10), name: n || ('f' + f) };
  });
  const cart = fs.readFileSync(path.join(DIR, 'game.p8'), 'utf8');
  const i = cart.search(/^__(gfx|label|gff|map|sfx|music)__$/m);
  const test = path.join(DIR, '_shot.p8');
  fs.writeFileSync(test, cart.slice(0, i) + driver(script, frames, maze, exec) + '\n' + cart.slice(i));
  if (fs.existsSync(DUMP)) fs.unlinkSync(DUMP);
  const r = cp.spawnSync(PICO, ['-x', test], { encoding: 'utf8', timeout: 120000, cwd: DIR });
  // printh lands on stderr on this install, not stdout
  const log = ((r.stdout || '') + (r.stderr || '')).split(/\r?\n/)
    .map(l => l.replace(/^INFO:\s*/, '').trim())
    .filter(l => l && !/^RUNNING/.test(l));
  log.forEach(l => console.log(l));
  if (!fs.existsSync(DUMP)) { console.error('no dump written'); process.exit(1); }
  const lines = fs.readFileSync(DUMP, 'utf8').split(/\r?\n/).filter(l => l.trim());
  const shots = {};
  for (const ln of lines) {
    const sp = ln.indexOf(' ');
    const name = ln.slice(0, sp), px = ln.slice(sp + 1).trim();
    if (px.length !== 128) throw new Error('bad dump row for ' + name + ': ' + px.length);
    (shots[name] = shots[name] || []).push(px);
  }
  for (const name in shots) {
    if (shots[name].length !== 128) throw new Error(name + ' has ' + shots[name].length + ' rows');
    let px = shots[name];
    let scale = 3;
    if (crop) {
      const [cx, cy, cw, ch, cs] = crop;
      px = px.slice(cy, cy + ch).map(r => r.slice(cx, cx + cw));
      scale = cs || 8;
    }
    const out = path.join(DIR, 'shot_' + name + '.png');
    writePng(out, px, scale);
    console.log('wrote', path.basename(out));
  }
  fs.unlinkSync(test);
}
main();
