// rotamaze - soak test. random input for thousands of frames across the
// whole pool, checking the invariants every frame. a pico-8 runtime error
// stops the cart, so simply reaching DONE is most of the point.
//   node soak.js [frames]
'use strict';
const fs = require('fs');
const path = require('path');
const cp = require('child_process');

const DIR = path.join(__dirname, '..');
const PICO = 'C:/Program Files (x86)/PICO-8/pico8.exe';

function driver(frames) {
  return `
-- soak driver (generated by tools/soak.js)
_ru=_update
_rd=_draw
sb=0 spb=0
function btn(b,pl)
 if b==nil then return sb end
 return (sb\\(2^b))%2>=1
end
function btnp(b,pl)
 if b==nil then return sb end
 return ((sb\\(2^b))%2>=1) and ((spb\\(2^b))%2<1)
end
srand(1)
tf=0 bad=0 wins=0 mz=0 cap=0
function fail(m)
 if bad<6 then printh("FAIL "..m.." at frame "..tf) end
 bad+=1
end
function _draw() end
function _update()
 tf+=1
 if tf==1 then
  loadmz(0)
  cap=mov+act
 end
 -- one random button per frame, often nothing
 local r=flr(rnd(9))
 sb=0
 if r<6 then sb=2^r end
 _ru()
 spb=sb
 if st==1 or st==2 then
  if pc<0 or pc>14 or pr<0 or pr>13 then fail("player off board") end
  if mov<0 or act<0 then fail("negative counter") end
  if pf<1 or pf>4 then fail("bad facing") end
  if #hs>cap then fail("history longer than the budget") end
  for i=1,210 do
   local w=bd[i]
   if w<0 or w>15 or w!=flr(w) then fail("bad wall value") end
  end
 end
 if st==2 then
  wins+=1
  st=1
 end
 if tf%400==0 then
  mz=(mz+1)%64
  loadmz(mz)
  cap=mov+act
 end
 if tf>=${frames} then
  printh("DONE frames="..tf.." wins="..wins.." fail="..bad)
  extcmd("shutdown")
 end
end
`;
}

function main() {
  const frames = parseInt(process.argv[2] || '4000', 10);
  const cart = fs.readFileSync(path.join(DIR, 'game.p8'), 'utf8');
  const i = cart.search(/^__(gfx|label|gff|map|sfx|music)__$/m);
  const test = path.join(DIR, '_soak.p8');
  fs.writeFileSync(test, cart.slice(0, i) + driver(frames) + '\n' + cart.slice(i));
  const r = cp.spawnSync(PICO, ['-x', test], { encoding: 'utf8', timeout: 600000 });
  const out = ((r.stdout || '') + (r.stderr || '')).split(/\r?\n/)
    .map(l => l.replace(/^INFO:\s*/, '').trim())
    .filter(l => l && !/^RUNNING/.test(l));
  out.forEach(l => console.log(l));
  fs.unlinkSync(test);
  const done = out.find(l => l.startsWith('DONE'));
  if (!done || !/fail=0$/.test(done)) {
    console.error('SOAK FAILED');
    process.exit(1);
  }
  console.log('soak clean');
}
main();
