// rotamaze - play every shipped maze inside the real cart.
// builds _test.p8 = game.p8 + a driver that loads each maze, replays the
// solver's plan through synthetic input, and asserts the cart reaches the
// win state with exactly the budget the pool says it should.
//   node verify.js [mazes.json]
'use strict';
const fs = require('fs');
const path = require('path');
const cp = require('child_process');

const DIR = path.join(__dirname, '..');
const PICO = 'C:/Program Files (x86)/PICO-8/pico8.exe';
const CHR = ['l', 'r', 'u', 'd'];

function driver(mazes) {
  const plans = mazes.map(m => '"' + m.plan.map(p => (p === 5 ? 'x' : CHR[p])).join('') + '"');
  const movLeft = mazes.map(m => m.movBudget - m.movOpt);
  const actLeft = mazes.map(m => m.actBudget - m.actOpt);
  return `
-- verify driver (generated by tools/verify.js)
_ru=_update
function _draw() end
sb=0 spb=0
function btn(b,pl)
 if b==nil then return sb end
 return (sb\\(2^b))%2>=1
end
function btnp(b,pl)
 if b==nil then return sb end
 return ((sb\\(2^b))%2>=1) and ((spb\\(2^b))%2<1)
end
pl={${plans.join(',')}}
el={${movLeft.join(',')}}
ea={${actLeft.join(',')}}
mi=0 ci=0 ph=0 oks=0 fails=0
function _update()
 if ci==0 then
  loadmz(mi) ci=1 ph=0 sb=0 spb=0
  return
 end
 local s=pl[mi+1]
 if ci>#s or st==2 then
  if st!=2 then
   printh("FAIL "..mi.." no win, "..(#s-ci+1).." presses left")
   fails+=1
  elseif ci<=#s then
   printh("FAIL "..mi.." won early with "..(#s-ci+1).." presses left")
   fails+=1
  elseif mov!=el[mi+1] or act!=ea[mi+1] then
   printh("FAIL "..mi.." left "..mov..","..act.." want "..el[mi+1]..","..ea[mi+1])
   fails+=1
  else
   oks+=1
  end
  mi+=1 ci=0
  if mi>=64 then
   printh("DONE ok="..oks.." fail="..fails)
   extcmd("shutdown")
  end
  return
 end
 if ph==0 then
  local c=sub(s,ci,ci)
  sb=0
  if c=="l" then sb=1
  elseif c=="r" then sb=2
  elseif c=="u" then sb=4
  elseif c=="d" then sb=8
  elseif c=="x" then sb=32 end
  ci+=1 ph=1
 else
  sb=0 ph=0
 end
 _ru()
 spb=sb
end
`;
}

function main() {
  const src = process.argv[2] || path.join(__dirname, 'mazes.json');
  const mazes = JSON.parse(fs.readFileSync(src, 'utf8'));
  const cart = fs.readFileSync(path.join(DIR, 'game.p8'), 'utf8');
  const i = cart.search(/^__(gfx|label|gff|map|sfx|music)__$/m);
  const test = path.join(DIR, '_test.p8');
  fs.writeFileSync(test, cart.slice(0, i) + driver(mazes) + '\n' + cart.slice(i));
  const r = cp.spawnSync(PICO, ['-x', test], { encoding: 'utf8', timeout: 180000 });
  const out = ((r.stdout || '') + (r.stderr || '')).split(/\r?\n/)
    .map(l => l.replace(/^INFO:\s*/, '').trim())
    .filter(l => l && !/^RUNNING/.test(l));
  out.forEach(l => console.log(l));
  const done = out.find(l => l.startsWith('DONE'));
  fs.unlinkSync(test);
  if (!done || !/fail=0$/.test(done) || !/ok=64/.test(done)) {
    console.error('VERIFY FAILED');
    process.exit(1);
  }
  console.log('all 64 mazes completed inside the cart, budgets exact');
}
main();
