pico-8 cartridge // http://www.pico-8.com
version 43
__lua__
-- rotamaze label generator
-- generated by tools/label.js - do not hand edit
hx="0123456789abcdef"

-- the player token, same shape as the in-game sprite
pl={"........",
    "...##...",
    "..####..",
    ".##..##.",
    ".######.",
    ".######.",
    "..####..",
    "........"}

function blob(px,py,g,s,col)
 for y=0,7 do
  for x=0,7 do
   if sub(g[y+1],x+1,x+1)=="#" then
    rectfill(px+x*s,py+y*s,px+x*s+s-1,py+y*s+s-1,col)
   end
  end
 end
end

-- a 2px wall on one side of a 16px tile
function wall(x,y,d)
 if d==0 then rectfill(x,y,x+15,y+1,7) end
 if d==1 then rectfill(x+14,y,x+15,y+15,7) end
 if d==2 then rectfill(x,y+14,x+15,y+15,7) end
 if d==3 then rectfill(x,y,x+1,y+15,7) end
end

-- clockwise arrow, the one motif the whole game turns on.
-- a runs backwards because pico-8's sin is screen-flipped: falling a
-- sweeps clockwise, from upper left over the top and down the right.
function arrow(cx,cy,r,col,t,hs)
 for a=0.44,0.0,-0.002 do
  circfill(cx+cos(a)*r,cy+sin(a)*r,t,col)
 end
 for i=0,hs do
  line(cx+r-hs+i,cy+i,cx+r+hs-i,cy+i,col)
 end
end

cls(0)

-- stone bands top and bottom
fillp(0x5a5a)
rectfill(0,0,127,6,7)
rectfill(0,121,127,127,7)
fillp()

-- title plaque
rect(6,10,121,46,7)
rect(8,12,119,44,7)
print("\^w\^trotamaze",32,20,7)
print("a maze that turns",30,36,7)

-- the board, four rows of six tiles at 16px
lay={"224382","e06286","428688","518034"}
for r=0,3 do
 for c=0,5 do
  local w=tonum("0x"..sub(lay[r+1],c+1,c+1))
  local x,y=16+c*16,54+r*16
  if w&1>0 then wall(x,y,0) end
  if w&2>0 then wall(x,y,1) end
  if w&4>0 then wall(x,y,2) end
  if w&8>0 then wall(x,y,3) end
 end
end

-- the exit shimmers at the far end
fillp(0x5a5a)
rectfill(98,56,109,67,7)
fillp()

-- the player and the arrow get a black outline so they stay separate
-- from the wall lines behind them
for ox=-2,2 do
 for oy=-2,2 do
  blob(16+ox,102+oy,pl,2,0)
 end
end
blob(16,102,pl,2,7)
arrow(56,94,11,0,3,7)
arrow(56,94,11,7,1,5)

printh("@@begin")
for y=0,127 do
 local s=""
 for x=0,127 do
  s=s..sub(hx,pget(x,y)+1,pget(x,y)+1)
 end
 printh(s)
end
printh("@@end")
extcmd("shutdown")
__gfx__
