// Turns tools/drafts.js (terrain) into tools/levels.js (playable levels).
//
// For each draft: backward-BFS the terrain, pick a start out of the layer named
// by `want`, then check it three ways before writing anything —
//   1. replay: walk the start down the layers using the *forward* move rule and
//      confirm it reaches a win in exactly `depth` moves. Cheap, and it is what
//      catches a reverse rule that doesn't mirror the cart.
//   2. deadTiles: no tile may have only fatal exits.
//   3. forward BFS from scratch, for the shallower levels where it is
//      affordable — an independent confirmation that `depth` really is optimal.
//
//   node --max-old-space-size=7000 bake.js

const fs = require("fs");
const path = require("path");
const drafts = require("./drafts.js");
const { deepen, pick, extract } = require("./deepen.js");
const { solve, deadTiles, parse } = require("./lib.js");

const BFS_UNTIL = 40;          // run the full forward BFS below this depth

const out = [];
let ok = true;
const fail = (i, name, msg) => { ok = false; console.log(String(i + 1).padStart(2) + " " + name.padEnd(20) + msg); };

drafts.forEach((d, i) => {
  const t0 = Date.now();
  const r = deepen(d.rows);

  const stuck = r.goals.filter((g) => !r.layers.some((L) => L.some((st) => st.bs.indexOf(g) < 0)));
  if (stuck.length) return fail(i, d.name, "UNREACHABLE GOALS " +
    stuck.map((g) => (g % 10) + "," + Math.floor(g / 10)).join(" ") + " — no box can ever be pushed onto them");

  const best = pick(d.rows, r, d.want);
  if (!best) return fail(i, d.name, "NO CLEAN START (every start has a box or the player on a goal)");

  const rep = extract(r, best.depth, best.st);
  if (!rep.ok) return fail(i, d.name, "REPLAY FAILED — " + rep.why);

  const dead = deadTiles(best.s);
  if (dead.length) return fail(i, d.name, "DEAD TILES " + dead.join(" "));

  let note = "replayed";
  if (best.depth < BFS_UNTIL) {
    const chk = solve(best.s, 8000000);
    if (!chk.ok) return fail(i, d.name, "forward BFS says UNSOLVABLE — " + chk.why);
    if (chk.moves !== best.depth) return fail(i, d.name, "forward BFS says " + chk.moves + " moves, not " + best.depth);
    note = "bfs-optimal";
  }

  const nb = parse(best.s).boxes.length;
  console.log(String(i + 1).padStart(2) + " " + d.name.padEnd(20) + nb + "box  " +
    String(best.depth).padStart(3) + " moves  " + note.padEnd(12) +
    "(" + r.states + " states, " + (Date.now() - t0) + "ms)");
  out.push({ name: d.name, s: best.s, moves: best.depth, boxes: nb, path: rep.path });
});

if (!ok || out.length !== drafts.length) {
  console.log("\nNOT WRITING levels.js — fix the failures above");
  process.exit(1);
}

const body = out.map((l, i) =>
  "// " + (i + 1) + " — " + l.name + " — " + l.boxes + " boxes, " + l.moves + " moves\n// " +
  l.path + "\n[\n" +
  Array.from({ length: 10 }, (_, y) => '"' + l.s.slice(y * 10, y * 10 + 10) + '"').join(",\n") + "],"
).join("\n");

fs.writeFileSync(path.join(__dirname, "levels.js"),
`// kanguroo level data — 16 levels, 10x10 each. GENERATED by tools/bake.js.
// . sand  # rock  ~ water  o goal  b box  B box on goal  p player
//
// Edit tools/drafts.js (the terrain) and re-run bake; do not edit this by hand.
// Every board is ringed with water, so no jump can be shortened against the
// edge. The comment above each level is one optimal solution, L/R/U/D.

const L = [
${body}
];

// one optimal solution per level, L/R/U/D — replayed by solve.js
const P = [
${out.map((l) => JSON.stringify(l.path)).join(",\n")},
];

const levels = L.map((rows, i) => {
  if (rows.length !== 10) throw new Error("level " + (i + 1) + " has " + rows.length + " rows");
  rows.forEach((r, y) => {
    if (r.length !== 10) throw new Error("level " + (i + 1) + " row " + y + " is " + r.length + " wide");
  });
  return rows.join("");
});

module.exports = { levels, rows: L, paths: P };
`);
console.log("\nwrote levels.js — " + out.length + " levels, " +
  out.reduce((a, l) => a + l.boxes, 0) + " boxes, " +
  out.reduce((a, l) => a + l.moves, 0) + " moves total");
