// kanguroo level data — 16 levels, 10x10 each. GENERATED by tools/bake.js.
// . sand  # rock  ~ water  o goal  b box  B box on goal  p player
//
// Edit tools/drafts.js (the terrain) and re-run bake; do not edit this by hand.
// Every board is ringed with water, so no jump can be shortened against the
// edge. The comment above each level is one optimal solution, L/R/U/D.

const L = [
// 1 — comb — 3 boxes, 22 moves
// URRDURDDLLUUDLLUUUDRUU
[
"~~~~~~~~~~",
"~........~",
"~.#.#.#.#~",
"~........~",
"~...o.o..~",
"~........~",
"~#.#.#.#.~",
"~.p.b.b..~",
"~..o...b.~",
"~~~~~~~~~~"],
// 2 — one gate — 4 boxes, 30 moves
// RDRDLDRUURLDDDLURURDLLDLURDRRU
[
"~~~~~~~~~~",
"~........~",
"~pbo.bo..~",
"~........~",
"~###.####~",
"~........~",
"~..o..o..~",
"~.b...b..~",
"~........~",
"~~~~~~~~~~"],
// 3 — the bridges — 3 boxes, 36 moves
// ULDLLUURRRDLLRDDDLUULDDDDDRRDRULDLLU
[
"~~~~~~~~~~",
"~........~",
"~...ob...~",
"~..b...b.~",
"~~~.~~~p~~",
"~........~",
"~..o..o..~",
"~........~",
"~........~",
"~~~~~~~~~~"],
// 4 — chicane — 4 boxes, 37 moves
// RRRULLRDDLLRULLURULLDRRLURRDLDDRULLDR
[
"~~~~~~~~~~",
"~........~",
"~.##..##.~",
"~.bo..ob.~",
"~.##..##.~",
"~.p......~",
"~.##..##.~",
"~.bo..ob.~",
"~.##..##.~",
"~~~~~~~~~~"],
// 5 — the long way home — 5 boxes, 45 moves
// RLDDDRRULULLLDLDRRLUURDURRRLLDDDURURRDDDULULL
[
"~~~~~~~~~~",
"~..~..~..~",
"~.o.pb.o.~",
"~....b...~",
"~~b.##..~~",
"~..b##.b.~",
"~........~",
"~.o.o..o.~",
"~..~..~..~",
"~~~~~~~~~~"],
// 6 — anvils — 3 boxes, 48 moves
// URRUURDLLDDDLURRRDRRUULLLLULDDRDRRDLULLURRUURDRD
[
"~~~~~~~~~~",
"~...#....~",
"~..o...b.~",
"~........~",
"~#b....#.~",
"~...o....~",
"~.b......~",
"~p#....o.~",
"~...#....~",
"~~~~~~~~~~"],
// 7 — four lakes — 4 boxes, 48 moves
// DRRRDRULLLURDRURRRLLRDRULLLLLLRRRDLLLURLDDRRULLL
[
"~~~~~~~~~~",
"~..~~~~..~",
"~p.~~~~..~",
"~o.b.b..o~",
"~......b.~",
"~........~",
"~o.....bo~",
"~..~~~~..~",
"~..~~~~..~",
"~~~~~~~~~~"],
// 8 — parity field — 3 boxes, 55 moves
// RRUUURDLDDRUDLURURDLUDDLDRUUUULLLRRULDLLDRRDRULULLLDRLD
[
"~~~~~~~~~~",
"~........~",
"~..o.....~",
"~......b.~",
"~.....o..~",
"~......b.~",
"~..o.....~",
"~p.....b.~",
"~........~",
"~~~~~~~~~~"],
// 9 — switchback — 3 boxes, 66 moves
// URRULURRULLLDDRDLURULDRRDLDRULURRULLLDDRDRRDLLLLLRULLURRULRDLDRRRR
[
"~~~~~~~~~~",
"~........~",
"~.b####..~",
"~o.......~",
"~b...####~",
"~......o.~",
"~####..b.~",
"~.o......~",
"~.p####..~",
"~~~~~~~~~~"],
// 10 — the channel — 5 boxes, 69 moves
// UURDLDRURDLUULDDRRRUUDLLUUULUURDLDRURRRDDUULLDLDDRUURDLUDDLURDRRRDLLU
[
"~~~~~~~~~~",
"~........~",
"~..o.~.bo~",
"~....~...~",
"~..o.~...~",
"~..b.~...~",
"~.bo.~..o~",
"~p.b.~.b.~",
"~........~",
"~~~~~~~~~~"],
// 11 — stepping stones — 3 boxes, 69 moves
// RRRUUULURDDLLLDDRRRLLUUURRDRULDLDRULLLUURURRDDDDURDLULULDLDDRRRUURDLL
[
"~~~~~~~~~~",
"~........~",
"~.~.~.~b.~",
"~........~",
"~..o..o..~",
"~.b~.~.~.~",
"~........~",
"~....ob..~",
"~p.......~",
"~~~~~~~~~~"],
// 12 — the cross — 4 boxes, 75 moves
// LULLDRURRDDDLLULUDRURRLDRRRURULDRDLUUUUURULDLLDDDRRLUURDRDDUULLDRRRDLULLLDR
[
"~~~~~~~~~~",
"~........~",
"~..b.....~",
"~.bo#.op.~",
"~##.##.##~",
"~..b.....~",
"~..o#.o..~",
"~.b......~",
"~........~",
"~~~~~~~~~~"],
// 13 — the slash — 4 boxes, 77 moves
// LLDRURDLRULDRDLUUUURDDRULULULRRRDDLLRULLDLDRUUDRULULRDLLDRUUURRDLLLULDDLUURDD
[
"~~~~~~~~~~",
"~..~.....~",
"~...~....~",
"~o...~...~",
"~.....~..~",
"~..o.p.~.~",
"~...o...~~",
"~..b.bbb.~",
"~...o....~",
"~~~~~~~~~~"],
// 14 — far shore — 5 boxes, 78 moves
// LLLDRDRRRDRUUULLDDDDRULRDLLUURDRDLDULDRRRUULDDRDLLDRURULLLULURDLDDDDUURDLLUURR
[
"~~~~~~~~~~",
"~...o..p.~",
"~.b.b.b..~",
"~..#.bo#.~",
"~~~~.~~~~~",
"~....b...~",
"~..o..o..~",
"~........~",
"~...o....~",
"~~~~~~~~~~"],
// 15 — box train — 4 boxes, 88 moves
// RRRDDDULRDDLLURDRUUDLLLUUURRRRLDLDRUUDRDRUDLLLUURURDRRDULRDDLUUUDLLULDRDRRRUUULDDDLUULUU
[
"~~~~~~~~~~",
"~p.......~",
"~.boooo..~",
"~........~",
"~.bb##...~",
"~........~",
"~..#..#..~",
"~......b.~",
"~........~",
"~~~~~~~~~~"],
// 16 — the pen — 5 boxes, 112 moves
// LLLDDDRRULDRDLLURLURDRDRURDLLURRULDLURRRUDRLLUURDDDRUUDDLURRULDLURRRDRURUUULLLDDDDDRDLURRUUULDRLDLURRRDRUULRDLUU
[
"~~~~~~~~~~",
"~......p.~",
"~.b#####.~",
"~..#o.o#.~",
"~.b#...#.~",
"~..#ooo#.~",
"~.bbb..#.~",
"~........~",
"~........~",
"~~~~~~~~~~"],
];

// one optimal solution per level, L/R/U/D — replayed by solve.js
const P = [
"URRDURDDLLUUDLLUUUDRUU",
"RDRDLDRUURLDDDLURURDLLDLURDRRU",
"ULDLLUURRRDLLRDDDLUULDDDDDRRDRULDLLU",
"RRRULLRDDLLRULLURULLDRRLURRDLDDRULLDR",
"RLDDDRRULULLLDLDRRLUURDURRRLLDDDURURRDDDULULL",
"URRUURDLLDDDLURRRDRRUULLLLULDDRDRRDLULLURRUURDRD",
"DRRRDRULLLURDRURRRLLRDRULLLLLLRRRDLLLURLDDRRULLL",
"RRUUURDLDDRUDLURURDLUDDLDRUUUULLLRRULDLLDRRDRULULLLDRLD",
"URRULURRULLLDDRDLURULDRRDLDRULURRULLLDDRDRRDLLLLLRULLURRULRDLDRRRR",
"UURDLDRURDLUULDDRRRUUDLLUUULUURDLDRURRRDDUULLDLDDRUURDLUDDLURDRRRDLLU",
"RRRUUULURDDLLLDDRRRLLUUURRDRULDLDRULLLUURURRDDDDURDLULULDLDDRRRUURDLL",
"LULLDRURRDDDLLULUDRURRLDRRRURULDRDLUUUUURULDLLDDDRRLUURDRDDUULLDRRRDLULLLDR",
"LLDRURDLRULDRDLUUUURDDRULULULRRRDDLLRULLDLDRUUDRULULRDLLDRUUURRDLLLULDDLUURDD",
"LLLDRDRRRDRUUULLDDDDRULRDLLUURDRDLDULDRRRUULDDRDLLDRURULLLULURDLDDDDUURDLLUURR",
"RRRDDDULRDDLLURDRUUDLLLUUURRRRLDLDRUUDRDRUDLLLUURURDRRDULRDDLUUUDLLULDRDRRRUUULDDDLUULUU",
"LLLDDDRRULDRDLLURLURDRDRURDLLURRULDLURRRUDRLLUURDDDRUUDDLURRULDLURRRDRURUUULLLDDDDDRDLURRUUULDRLDLURRRDRUULRDLUU",
];

const levels = L.map((rows, i) => {
  if (rows.length !== 10) throw new Error("level " + (i + 1) + " has " + rows.length + " rows");
  rows.forEach((r, y) => {
    if (r.length !== 10) throw new Error("level " + (i + 1) + " row " + y + " is " + r.length + " wide");
  });
  return rows.join("");
});

module.exports = { levels, rows: L, paths: P };
